### ISSUE TITLE
solid color overlaps

### ISSUE THREAD

**Issue by florafuchsia** [surfbryce/beautiful-lyrics#1]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/132691780/66ddeee3-1aa3-480d-9ec6-6ae5853274a4)
the gradient shows underneath the solid color at the bottom but its not on top

**Comment by surfbryce** [comment]
I think this might be an issue with the older styled versions of the client not having the right CSS classes to work - I'll see if I can get on an older styled version to see if I can replicate this.

**Comment by surfbryce** [comment]
Yeah I'm not sure why it would be doing that - even with the "Library X View" Expiremental Feature turned off.

Can you check whether or not your client is updated to the newest version at all? You would do that by clicking your pfp and then seeing if "Update Spotify Now" is a dropdown option. I've had some issues be caused by this from other people.

**Comment by aunight** [comment]
I don't have that icon in your preview too

**Comment by aunight** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/52199445/1154dffd-6cf2-4c3c-aaea-49b8e05bb87a)
This my Spotify version.
Is this not the newest version?

**Comment by surfbryce** [comment]
> ![image](https://user-images.githubusercontent.com/52199445/238898640-1154dffd-6cf2-4c3c-aaea-49b8e05bb87a.png)
> This my Spotify version.
> Is this not the newest version?

also this is the latest version - are you experiencing the same issue that the creator of this post is or is it just that you don't have that icon?

**Comment by aunight** [comment]
Yes it work thanks for help and amazing extension

**Comment by florafuchsia** [comment]
yup! the experimental features fix did it for me thanks!
