### ISSUE TITLE
Error message "spotify can't play this right now"

### ISSUE THREAD

**Issue by JuniperInk** [surfbryce/beautiful-lyrics#103]
I get an error message that states: "spotify can't play this right now. If you have the file on your computer you can import it." I assume its from the lyrics loading in? The message repeats if you skip, shuffle, loop, pause, or play. The extension works great, lyrics, background, everything, it's just that weird popup error. (I know it's the extension for when I uninstalled it the error stopped) thanks!

<img width="348" alt="Screenshot 2023-08-07 at 3 29 40 AM" src="https://github.com/surfbryce/beautiful-lyrics/assets/141631614/a7cc0908-a5d6-4cdd-8916-646eb7733b38">

**Comment by surfbryce** [comment]
@JuniperInk This is not an issue with the extension (as in the error is not caused by the extension). I do not interfere with playback whatsoever.

This error can appear in Spotify randomly from time to time and it can happen for any extension. I would recommend reinstalling Spotify from the Spotify website.
