### ISSUE TITLE
Bug With Bloom Theme

### ISSUE THREAD

**Issue by andiricum2** [surfbryce/beautiful-lyrics#109]
Enter Cinema button and Close Page button at the top of the lyrics page are not showed correctly.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/62946099/235a12fa-f3a5-4122-bf71-360d764fe806)

**Comment by zakaryan2004** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/29994884/1dd02c60-2969-47b4-828e-bf9f335d365e)
In my case, the buttons aren't even visible at all

**Comment by surfbryce** [comment]
I did make a fix for this but they must've updated something to undo my change or changed something else to make it still appear. Will look into this

**Comment by surfbryce** [comment]
Alright @andiricum2 and @zakaryan2004 the issue was actually with Bloom and how they handle the top-bar offset. I've went ahead and made a patch in my CSS so that it undoes what messes up the whole thing.

Also @zakaryan2004 hover over the page and they will appear just FYI.

You guys should see this in the next update (which will be today.)

**Comment by andiricum2** [comment]
Thanksss 🙃
