### ISSUE TITLE
different font when first open lyrics page

### ISSUE THREAD

**Issue by CHRISTYRELL456** [surfbryce/beautiful-lyrics#116]
When I click on a song it shows a different font. I don't know if this is an attempt at trying to add a different font and it failing or a bug that is not intended to be happening. the font shows for about 1 second then fixes itself

**Comment by surfbryce** [comment]
@CHRISTYRELL456 A screen recording would be awesome to have!

This would be an issue with the browser-renderer (what Spotify uses to show you stuff) since the font is done in CSS and not programatically.

**Comment by CHRISTYRELL456** [comment]
Ok ill have it here in a bit. Sorry for the late response, I wasnt home for the weekend

**Comment by CHRISTYRELL456** [comment]
@surfbryce its not wanting to happen right now, but when it does happen ill let you know

**Comment by CHRISTYRELL456** [comment]
@surfbryce Here you go
https://github.com/surfbryce/beautiful-lyrics/assets/102339335/2cb9c4ac-2f08-4b37-aad6-5eafa7c1950a

**Comment by CHRISTYRELL456** [comment]
I know you probably busy, but im an inpatient person and it would be nice for a resonse. If this seems rude, its not i just remind people who havent replied to me in a few days to get back to me when they can. Thank You!

**Comment by surfbryce** [comment]
@CHRISTYRELL456 Yeah I'm a game developer that manages several small teams that combine to be about 10-12 people. I do this on the limited free-time that I do have.

I can understand though as I myself am impatient; so I do appreciate the self-recognition here. It could be interpreted as rude by others but your honesty here allows me to see it as otherwise.

To be completely honest with you I don't have an exact reasoning as to why this is happening. As I've explained the font is handled by the browser-rendering engine that Spotify uses to render everything on your screen. Technically, this is not a bug with the underlying code of the extension (at least when isolated).

However, I am suspecting that it is possible that your theme may be overriding the font temporarily before some event triggers a priority re-evaluation which then my font goes on top. Again I am only suspecting this and highly doubtful since I don't know why it would just go to the default browser font rather than Spotifys own.

Would you mind sharing the theme you are using? This is the only way I can get rid of my speculation.

Otherwise all there is left for me to assume is that your Spotify is having some sort of font-caching error or something which is causing it to be unloaded and then having to be reloaded.

So I can't really formulate an exact solution because this could be an issue that a simple Spotify reinstallation could fix.

**Comment by CHRISTYRELL456** [comment]
I'm currently using the Dribbblish theme with the lunar option selected. Thank you for understanding and not taking it in a bad way.
