### ISSUE TITLE
Disabling this bar

### ISSUE THREAD

**Issue by cheesethesylveon** [surfbryce/beautiful-lyrics#117]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/85301596/3232cd76-4ee6-4b15-9078-26496e3f0d1b)
Would make it cleaner for displaying on a screen (e.g at a coffee). Great extension btw!

**Comment by surfbryce** [comment]
@cheesethesylveon Originally I didn't want to mess with the bar-background in Cinema mode since I felt like it would be encroaching on the actual CSS beyond what I would really need to modify.

However, I do agree that it can be off-putting depending on the theme.

What theme are you using here?

**Comment by cheesethesylveon** [comment]
I'm currently using the "Bloom" theme. Also it's weird because themes compatibility is pretty much non existent, i had trouble with some themes (like buttons not reachable on Bloom)

**Comment by surfbryce** [comment]
@cheesethesylveon I'm not sure what themes you've tried but there is a lot of built-in support to override certain characteristics that themes have to make the extension look and work properly.

Themes are visual modifiers and because of that I can't exactly account for all possibilities when developing since I use the vanilla Spotify theme. However - when people *do* submit issues with specific themes - I always fix them.

In this case this isn't really a lack of support but more or so a conscious choice I made when first encountering this with other themes.

But of course I now see this as visual clutter which is what I aimed to get rid of initially.

So, if there are issues with themes that you run into please feel free to make an Issue here on GitHub about it. Again, these themes are updating all the time and changing things that can cause my stuff to be inaccessible or not look right. I rely on people using my extension to be able to report these so I can fix them.

You should see this work properly in the next update (which should be out today)
