### ISSUE TITLE
Song starts playing automatically on startup

### ISSUE THREAD

**Issue by XASAZA7** [surfbryce/beautiful-lyrics#127]
Hello, since updating Spicetify from 2.22.2 to 2.23.0 (and therefore BetterLyrics 3.1.12 to 3.1.13), every time I open Spotify the current song would start playing automatically. I noticed that after disabling BetterLyrics it would no longer do that.
Is it a bug or is there any way I can change that behaviour? Although it seems unlikely because it didn't use to do that before.

**Comment by surfbryce** [comment]
@XASAZA7 Yeah so basically Spotify made some changes to their internal stuff that messed with some things that I check for.

The latest version of this should account for that and I've recently purged the JSDelivr CDN (which marketplace uses) so that users don't run into this issue. Don't expect it to do that anymore, at most it'll take a day. I appreciate you reporting this issue though!

**Comment by XASAZA7** [comment]
Hi, sadly the problem is still occurring. Is it something on my end or has it not been patched yet?

**Comment by surfbryce** [comment]
@XASAZA7 What version of Spotify/Spicetify are you on?

**Comment by XASAZA7** [comment]
Spotify is on version 1.2.19.941.gbf202593 and Spicetify is on v2.23.0

**Comment by surfbryce** [comment]
@XASAZA7 Yeah it's a bit odd that it is still happening for you since everyone else I know who had this issue said it was resolved after the update.

What I recommend is first uninstalling the extension and then reinstalling it. If it is still happening I don't know if there is much I can do other than say to reinstall Spotify.

**Comment by XASAZA7** [comment]
Okay, I'm going to reinstall it right now and I'll let you know. Thank you for the help

**Comment by XASAZA7** [comment]
I've reinstalled Spotify and Spicetify, but again, as soon as I enable the plugin via the marketplace, the current song immediately starts playing.
I really don't know what to do at this point... perhaps installing it manually could help?

**Comment by surfbryce** [comment]
@XASAZA7 Let me ask you this; is the update notification still popping up for you or no?

**Comment by XASAZA7** [comment]
Uhm, it kept popping up as soon as I updated Spicetify from 0.22.2 to 0.23.0 the very first time or reloaded the client, but like, after totally closing Spotify and opening it again it would no longer appear but the song kept playing automatically anyway.
Now, after reinstalling Spotify and Spicetify, the update notification popup didin't appear at all (well, probably cause it was already up to date this time)

**Comment by surfbryce** [comment]
@XASAZA7 Yeah it's to be expected that it doesn't popup anymore. Was just making sure that Marketplace wasn't weirdly storing the old version or anything.

I'll have to take a deeper look into this later. Spotify may have changed another property name or Spicetify might've changed something I'm not sure. I'll put this back open for now as I investigate.

**Comment by XASAZA7** [comment]
Oh okay, it's very odd that this is still happening...my gf also has the same problem and it hasn't been fixed for her either so yeah, I really don't know. The marketplace says the extension's last update was on August 30th btw, I don't know if it's intended to be this way or not. Thank you very much anyway :)

**Comment by snowsharkt** [comment]
I'm facing the same issue, hope it will be fixed soon

**Comment by Skellingtor** [comment]
Forced the extension to update and the issue stopped for a moment, but it came back the next day. Hoping it can be fixed soon!

**Comment by KK-Designs** [comment]
I'm having the same issue. Hope it'll get fixed soon

**Comment by RaspberryKitty1** [comment]
I have same issue as well....

**Comment by KK-Designs** [comment]
> I have same issue as well....

They said they're working on it, [Source](https://github.com/surfbryce/beautiful-lyrics/issues/138#issuecomment-1708884834). Hopefully it'll get done fast

**Comment by mortein-powerkiller** [comment]
yo please fix this, it's been a while. It's a jumpscare every time I open spotify.

**Comment by surfbryce** [comment]
@XASAZA7 @Skellingtor @RaspberryKitty1 @KK-Designs @mortein-powerkiller @snowsharkt The issue should now be fixed. Spotify updated their property names a month ago or something like that and I did appropriately update to accommodate those change then but I forgot to do so in the place where I get the initial pause state. This caused my syncing method to think that we weren't paused and then cause it to "resume".

This is now fixed and uses the right property name. You should see this fixed in the next update!

**Comment by KK-Designs** [comment]
@surfbryce It still seems broken to me. It says it auto-updated, so I restarted my Spotify client, and it still auto-plays. Restarted again just in case, and the same outcome. Even after uninstalling and reinstalling the extension, the same thing is happening. Not sure why.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/71038229/81b22166-ff24-4b20-87de-7d00af3aa270)

**Comment by surfbryce** [comment]
@KK-Designs I'll reopen this in that case, I have no idea why it's still auto-playing for you - I can't get it to happen for me at all so it's a little odd.

**Comment by RaspberryKitty1** [comment]
yea same with mine

**Comment by KK-Designs** [comment]
Also, how do I change styles? Right now the entire row slowly glows until that verse is finished, how do I change it to look like the one in the preview?

**Comment by surfbryce** [comment]
@KK-Designs Please refrain from putting unrelated questions in issues please. If you need to ask that question make an issue that has (Question) in the title.

To answer your question: different songs have different types of synced lyrics (Static, Line, and Syllable) this is completely dependent on the artist/label and how much effort they put into submitting the lyrics of the song.

There is no option to change it because it's completely reliant on the data provided. If it's going line by line that's the best my extension could get. If it goes by syllable/word that's the absolute best possible. Etcetera for the other possibilities.

**Comment by KK-Designs** [comment]
@surfbryce I see, will do the new issue with question tag for any future questions, sorry

**Comment by XASAZA7** [comment]
The latest update actually seems to have fixed the issue, at least for me.

**Comment by RaspberryKitty1** [comment]
seems the issue has been solved for me as well. no more ear blasting music on Spotify startup X3

**Comment by surfbryce** [comment]
Alright going to give this another day to see if it came back and if it doesn't I'll close this. Hopefully the changes I made fix this once and for all

**Comment by KK-Designs** [comment]
I don't know why but it's working for me now, I guess the auto-updater broke because it was showing that it updated every time I reloaded, making me think that it actually didn't upgrade. But now it has updated and is working correctly, maybe all it needed was a system restart

**Comment by surfbryce** [comment]
Alright seems to be fine now, going to close this!
