### ISSUE TITLE
(Suggestion) Closing Lyrics View should maintain scroll-state from previous Page

### ISSUE THREAD

**Issue by nishatrhythm** [surfbryce/beautiful-lyrics#129]
I've encountered while using **Beautiful Lyrics** with Spotify. In the main Spotify app, when I open the lyrics feature and subsequently close it, Spotify conveniently remembers my scrolling position. However, I've noticed that when I open **Beautiful Lyrics** and then close it, the scroll view resets to the top of the app. This inconsistency in scroll view retention has been somewhat frustrating for me.

**Comment by surfbryce** [comment]
@nishatrhythm You’ll need to be more specific with what exactly you expect here.

Are you saying that when it is actively scrolling and you reopen the lyrics view it doesn’t go back to the current lyric properly? Or are you saying that when it’s not actively scrolling and you scroll it yourself it doesn’t go back there?

It should always go back to the active lyric when you reopen the lyric view; no matter if it is playing or not.

If this is the behavior that is broken then I’ll rename your title to fit in line.

If you’re expecting it to go back to the scroll position you went to when it was inactive or actively scrolling then this will never be implemented. It doesn’t make much sense at all to have that feature as when you scroll through the lyrics it’s so you can jump between timestamps (click on the lyrics itself).

The only place I can see this being beneficial is with static lyrics.

**Comment by nishatrhythm** [comment]
Sorry for the confusion. I am adding a video soon. There is no issue inside the lyrics view.

**Comment by nishatrhythm** [comment]
@surfbryce 
https://youtu.be/9M9oe3e6Sag
Every time I turn off full-screen view or the 'Better Lyrics' lyrics view, the screen goes at the top of the Liked Songs list. However, I didn't encounter this issue when using Spotify without the 'Better Lyrics' extension. Thank you in advance for your assistance.

**Comment by surfbryce** [comment]
@nishatrhythm So in a technical sense this is actually not a bug with the extension itself.

When the lyric-views are opened (fullscreen, cinema, page, etc.) they force Spotify to navigate to a different page. Which causes the content in the center page to change.

The simplest view we can talk about here is the page lyrics view. This forces the center page to change to display the lyrics, imagine it like clicking on a website URL and it bringing you to a different page. In Spotify, state does not persist across page-changes; and so - from a built-in perspective - it's impossible.

What I can do though is I can keep a local persistence of what the page-scroll state was so that when you close a lyrics view it'll restore properly.
