### ISSUE TITLE
(Suggestion): Add option to Disable Progress-Effect on Line-Synced lyrics

### ISSUE THREAD

**Issue by castdrian** [surfbryce/beautiful-lyrics#136]
I personally find the downwards scroll unsettling and would like to force LTR scrolling

**Comment by surfbryce** [comment]
@castdrian You're going to have to show an example of what you mean.

No where have I seen left to right scrolling for lyrics on any application I’ve ever used (Spotify, Apple, Tidal, whatever else).

Downwards scrolling is the default everywhere and there is no configuration to change that on anything else as well.

**Comment by castdrian** [comment]
well that was perhaps a brain stupidity, not sure why I chose scrolling, but what I am actually referring to is the glow animation that goes along with the timestamps of the timed lyrics, excuse the idiotism within the choice of words

**Comment by surfbryce** [comment]
@castdrian I won't add an option to make it scroll left-to-right because inherently this is misleading when reading it.

At least when its scrolling downwards you get an idea of the progress and aligns with the actual lines of text really well most of the time. This is because the precision when it comes to lines is much lower than that of words and so it's less noticeable and more likely to be in sync.

What I can do though is add an option to make it so the progress-effect is not present.

**Comment by castdrian** [comment]
I mean that is a bit confusing since imo the existing left to right fill effect is a way better progress indicator than the top to bottom filling, especially when reading hangeul top to bottom just doesn't really indicate any progress whatsoever, and it is weird that it randomly picks one of the two per song

**Comment by surfbryce** [comment]
@castdrian Ah, yeah so you're confused.

There are three different type of syncing modes: Static, Line, and Syllable (some people say word).

When I grab the lyrics from the lyrics providers I choose the best synced version.

These lyrics given to these providers are given to them by the Record Label/Artists themselves.

So the "left to right" fill you are talking about is the Syllable synced version. The effect you see there is not at all the same as what is happening in the Line-synced version. The syllable synced version actually has timestamps for the syllables themselves and they are being animated likewise. In the line synced version we only have a timestamp for the entire line itself.

To address your randomly picking concern, it's not randomly picking. Some songs have artists/labels that have put in the effort to sync lyrics in-depth (syllable sync), some have only done surface level (line sync), and some just opt-in to just displaying the lyrics themselves as text (static).

There's nothing I can do to make syllable-synced lyrics be available for every song; the best synced version of the lyric is up to the record label/artist.

**Comment by castdrian** [comment]
I see that indeed was majorly helpful in understanding what's happening, I was not aware that the depth of synced lyrics extends beyond entire lines, I know do see what is happening and why, please once again excuse my idotism, this has been quite helpful

**Comment by surfbryce** [comment]
@castdrian No problem, you're definitely not the first person to be confused by it.

I've used Apple Music for a long time before Spotify and so I have always been accustomed to the syllable-synced lyrics being available on a majority of songs and likewise for line-synced.

For Spotify users it's a new concept since line-syncing is relatively new and syllable-lyrics are no where to be seen yet.

I'll close this for now unless you think there is something that can be done suggestion wise: then I will reopen it for that.

**Comment by castdrian** [comment]
actually, I used my brain again and came up with a question, wouldn't it be possible to still do a left to right anim for the entire line rather than per syllable?

**Comment by surfbryce** [comment]
@castdrian I answered this before.

The left to right animation for an entire line will always be misinterpreted as the words at a certain point being said rather than it being an indicator of how far the lyrics have come.

The vertical animation will always interpreted as how far into the line we are.

Additionally, left to right for an entire line breaks apart when a lyric gets split up into multiple lines.

There’s no proper or good way to do left to right on just a line. My vertical solution is good and natural for indicating how far a lyric has come (even better for those who are deaf).
