### ISSUE TITLE
main page and fullscreen doesn't work

### ISSUE THREAD

**Issue by BetaDv** [surfbryce/beautiful-lyrics#139]
https://www.youtube.com/watch?v=jSyoe0Tardo&ab_channel=BetaDv
- i apologize for bad audio quality

I'm using the theme "Spicetify Galaxy", however this didnt work on other themes, nor the default spotify without any extensions or anything other than Beautiful Lyrics and Lyrics-Plus installed

**Comment by surfbryce** [comment]
@BetaDv Thank you so much for the video - really helps me to see what's going on!

If you don't mind could you run the command "spicetify apply enable-devtools" and then right click on any open space that doesn't trigger Spotifys popup menu, go to Develop and then Developer Tools.

Once you're there go to the Console tab and screenshot everything there. This will be extremely helpful!

**Comment by BetaDv** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/62099784/bfaeed66-bbee-474c-8370-23a2eddf6af8)
sorry I dont know if this is the right thing, also I never got the notification, im sorry for late response

**Comment by sinrn** [comment]
I believe I am experiencing a similar error. In my instance, I cannot open the fullscreen option, and when I try to I get a blank gray screen in the area where the home page/marketplace/lyrics usually appear when you navigate to it. Otherwise, everything else works fine, the beautiful lyric button shows the lyrics and background correctly, I just cannot use the fullscreen or cinema button without the gray screen. I've tried removing all themes and extensions to make sure it wasn't a conflict. All other extensions/themes work fine.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/143914567/9445085d-1367-4ff1-a469-126a2137f8fc)

Here's the error I'm getting
