### ISSUE TITLE
Support LRC File

### ISSUE THREAD

**Issue by aroxu** [surfbryce/beautiful-lyrics#146]
I think it is great that it has lrc support.

**Comment by surfbryce** [comment]
@aroxu There is currently a lyrics creator/editor in the works right now for the extension, so that you can easily make/sync lyrics for songs. When you've done so it'll save locally for you but also send a copy of what you made to the backend server so that it can be reviewed. If it's accepted it will then be the official lyrics for that song and everybody will see your synced lyrics. This is so the community can properly sync lyrics to songs and eventually community moderators can approve them (when this initially releases it will just be me).

So there is no plan to support external file types and etc. You'll have to wait for this feature.

**Comment by aroxu** [comment]
It'll be great to save different lyrics for one song, such as Japanese lrc to Roman, etc... and users can change other variants of lyrics.
Which is already implemented in a program called [ALSong](https://altools.co.kr/product/ALSONG) in Korea.

Here are some screenshots:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/30624945/80021333-7d49-4431-868c-c66c4467d9ce)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/30624945/5a29c3d5-be75-4020-a88a-2467b2dbe5de)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/30624945/fbebac68-74b5-4255-800e-1eecc89898d6)
