### ISSUE TITLE
(Question) Pseudo lyric sync

### ISSUE THREAD

**Issue by GalexY727** [surfbryce/beautiful-lyrics#148]
For songs that have timestamps for each line, but not for words, would it look nice to have a scroll through the words left to right with the glowing effect, using the timestamp of the next line as the end goal, per se. Basically, instead of going top to bottom with the animation, go left to right. Was this attempted and found to be inconsistent due to tempo? Obviously, there are songs that hold a single word or pass by a word faster or slower than others uniformly, though knowing the start of the next line gives some sort of relativity.

**Comment by surfbryce** [comment]
@GalexY727 This is never going to be implemented because it's misleading. If you have left-to-right indication for a line that is line-synced it makes it seem like the progression is the same as a syllable synced line/lyric.

The top to bottom animation tells you how long the line lasts and how far into it we are. It's not supposed to tell you how many of the words/characters we have gone through, just the line itself. When we go from left-to-right we are now telling the user visually that this is how many words/characters we have gone through. It gives a different visual indicator.

The top to bottom effect is very clear and tells you that this is the line progress not anything else. Left to right can be confused as more than that very easily.

**Comment by GalexY727** [comment]
That makes sense, thanks for getting back to me so quickly. How do you get if a song is syllable synced? I was curious if it was possible to add songs to the system if I wanted to.

**Comment by surfbryce** [comment]
@GalexY727 At the end of the day it comes from a service called Musixmatch. You can be a curator on there if you want.

I am working on a feature for the extension which will allow for community contributions straight from Spotify which will be moderated and if a synced submission is accurate it will be used as the version for everybody else.

This won't come for a while though. So for now your best bet is through Musixmatch.

**Comment by GalexY727** [comment]
I had figured, thanks!
