### ISSUE TITLE
Slowly(unsync) and incorrect Lyric

### ISSUE THREAD

**Issue by Marmur2020** [surfbryce/beautiful-lyrics#168]
The hardkiss - Два вікна

Correct: 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/109208530/6245a7a4-f4db-436e-8a52-0c503e6dcc06)

Incorrect(end) and slowly(unsync) animated text(left to right):
![image](https://github.com/surfbryce/beautiful-lyrics/assets/109208530/d1f4d6e2-441d-417a-a7a4-38e381957d08)

**Comment by surfbryce** [comment]
@Marmur2020 Neither one of these is correct/incorrect.

Lyrics are not created/generated by the extension. These lyrics are grabbed from various sources and then the best one is used. These lyrics are submitted by the artists/labels themselves; so in other words, the artist/label of this song chose to separate these words onto their own lines.

So, this is not an issue with the extension and is the choice of the artist/label.

**Comment by Marmur2020** [comment]
@surfbryce I don't know how your algorithm works and from what sources the algorithm is taken, but I see that it doesn't work correctly and there are no repetitions 4 times, there are only 2 times. The fact that the label or artists release songs immediately and there is already the right text taken, I don't see the point of giving the algorithm to find from other sites, not immediately on trusted sources such as Youtube. It was better if people corrected, not some obscure site. And yes I realise that you didn't quite understand me at first because I didn't write in detail. 

To put it succinctly, algoritm doesnt work correctly.

Algoritm:
- Два вікна
- Два вікна
- Два вікна
- Два вікна

Source: https://www.youtube.com/watch?v=gCsoQunAjoA (description Lyric)
Correct lyric from Official Music Video:
- Два вікна
- (ааааааа)
- Два вікна
- (ааааааа)

**Comment by surfbryce** [comment]
@Marmur2020 The sources used are Apple Music and Musixmatch (which every major Streaming provider uses for lyrics including Apple Music) for syllable synced lyrics.

There is no "algorithm". It simply retrieves lyrics from these primary-sources. On the client-side Spotify is used for line-synced lyrics but I have to fall back to the primary-sources for this since Spotify has recently made lyrics Premium-Only.

So I am not getting it from some "obscure" site as you are insinuating and I'm definitely not using an "algorithm" to scrape the lyrics off the web.

The lyrics being used for this song are from Apple Music which primarily relies on Musixmatch for syllable-synced lyrics or relies on direct-submission by the artist/label (Apple Music has their own program for artists/labels to submit lyrics to just like Musixmatch does).

Like I said, these are the lyrics that the artists officially submitted. YouTube is not a trusted source either and they don't have a direct API to get lyrics from anyways.

So, I'll put it this way for you: These lyrics are being retrieved from the most credible sources and APIs you can find on the entire internet and are what provides lyrics for every major service out there - I can't fix it because this is what is registered in their databases - it's not my problem nor the extensions.

In the future there will be an Editor so community contributions can be made. When that comes out you can refine the syllable-synced version.

What I'm assuming happened is the label is who submitted the lyrics for the song and they misheard the track and assumed it was being repeated four times. This happens time to time when the label is who submits the lyrics and not the artist (where certain phrases/words are misinterpreted).

**Comment by Marmur2020** [comment]
@surfbryce Sorry I didn't even look at the code in detail, only now I realized that there is no alorhythm there is only Spotify and Apple Music text parser. Well, and I didn't know how the code worked.  I like this extension anyway. I don't think it's your fault because you made it possible to make animated text. And thank you for this).
