### ISSUE TITLE
Remove the original lyrics button

### ISSUE THREAD

**Issue by andrewgr1234** [surfbryce/beautiful-lyrics#169]
the plugin adds a button for the beautiful lyrics so why do i need to also have the original lyrics button? its just taking up space.
remove it or add the option to turn it off and on

**Comment by surfbryce** [comment]
@andrewgr1234 Enable "Show lyrics in the right sidebar" in Experimental features to remove it. I'll add this to the FAQ but the extension won't add a toggle for the original (since technically it already exists built-in) and won't forcefully remove it since people use Spotifys built-in in conjunction with my extension.

Experimental features usually get forced upon users eventually (the right sidebar was once experimental only and then officially released) and the option I mentioned will be one of them.
