### ISSUE TITLE
Theme "marketplace" Issues

### ISSUE THREAD

**Issue by johnnyjohnboyboy** [surfbryce/beautiful-lyrics#175]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/53444998/b86c6628-e35d-4595-a421-af71ca2e0eec)
I'm on the Spicetify marketplace theme and all I get is a blank page whenever I load up the lyrics to any song.

I also see these three icons at the top of the application.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/53444998/3e6538b7-91e6-45e0-98ad-fb817778ca69)

**Comment by johnnyjohnboyboy** [comment]
damn, has no one found a solution? i can post a more clearer screenshot of my problem if you'd like

**Comment by surfbryce** [comment]
@johnnyjohnboyboy Sorry I haven't gotten to this sooner. The main issue is that these type of problems aren't easy to diagnose sometimes. Sometimes you have to update Spicetify or completely reinstall Spotify.

Try both of these things, if they fail, then run the command "spicetify apply enable-devtools", right click on any open space that doesn't trigger the Spotify right-click menu, then go to Developer and Developer Tools, go to the console tab, and screenshot everything there.

I think I didn't respond sooner because I was going to add these instructions to the FAQ so then I could direct you there but I haven't done that yet so I'm replying now.

**Comment by johnnyjohnboyboy** [comment]
Ah, gotcha. Thank you for clarifying.

**Comment by johnnyjohnboyboy** [comment]
It works now after I updated spictify. Thanks!
