### ISSUE TITLE
How can i change the effect of the lyrics?

### ISSUE THREAD

**Issue by Tregua93** [surfbryce/beautiful-lyrics#178]
I've just installed the Extension in Spotify and setting up all the experimental features required, but the lyrics is set on the vertical effect. I've seen in the readme the horizontal effect on the single word, but i cannot see where to changes these effect.
Can you tell me where i can change this settings?

**Comment by surfbryce** [comment]
@Tregua93 Certain songs will have syllable-synced lyrics and others will not. This is up to the artist/label that submitted the lyrics for the song. There are no settings as this is automatic, if a syllable-synced version is available it will use that.

Too many people have asked this question because they don't understand how these type of things work (which is understandable; Spotify has never had this feature and if you're not coming from Apple Music than you'll never have had the opportunity to experience this before). So I'll add this to the FAQ explaining how this works.
