### ISSUE TITLE
Full Screen Song Problem

### ISSUE THREAD

**Issue by user-name-user** [surfbryce/beautiful-lyrics#183]
So the lyrics view is indeed better than the normal one, but if you install this extension and go in the fullscreen listening the UI gets so much worse than the default one. I am going to attach some photos in the comment, the first one is without the extension, and the second one is with the extension.
![Screenshot 2023-11-04 233851](https://github.com/surfbryce/beautiful-lyrics/assets/135058132/71cc3d40-691a-4ca2-87a3-2f3871a8f2d9), As you can see here, the UI is very good without any problems. if i want i can click on the lyrics button to show the lyrics.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/135058132/3a0c7e9c-76c7-44ba-8e5f-ad663f36b9e1), this is how it looks like with the extension enabled. the UI is terrible! Yes, if the song does have lyrics they will get shown on the right, and they look good, but the rest of the UI sucks

**Comment by surfbryce** [comment]
@user-name-user Negatively stating nothing is a great way to get your “feedback” ignored. If you can start with what can be improved (and not just saying it “sucks”) then something can be done.

This type of UI pattern is pretty standard across streaming platforms and Spotify is really the outlier here on desktop.

What are the specific pain-points you’re encountering here? What would you prefer (and do you have any examples)?

How you presented your “feedback” is a terrible way to get any change implemented. I would work on improving your tone in the future.

**Comment by user-name-user** [comment]
> @user-name-user Negatively stating nothing is a great way to get your “feedback” ignored. If you can start with what can be improved (and not just saying it “sucks”) then something can be done.
> 
> This type of UI pattern is pretty standard across streaming platforms and Spotify is really the outlier here on desktop.
> 
> What are the specific pain-points you’re encountering here? What would you prefer (and do you have any examples)?
> 
> How you presented your “feedback” is a terrible way to get any change implemented. I would work on improving your tone in the future.

I didn't mean to be rude, what i am saying is that it completely re does the fullscreen view, and this new fullscreen view is bad for numerous reasons, first of all theres problems with other extensions, as you can see the star rating is overlapping the author name, it also lacks customization. an extension called Full Screen does this much better because it offers a lot of settings to customize just for this single page. it also has lyrics integrated. look the difference, this looks so much better
![image](https://github.com/surfbryce/beautiful-lyrics/assets/135058132/830f0b57-cfce-455b-b658-b77249383588), first of all its just better overall. no overlapping and errors between extensions, but the ui is just better, it also has built in lyrics as well, look. 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/135058132/475770df-560b-457d-b5ca-c6a9752d1535)
and look how many settings avaible, 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/135058132/c135b777-bbc6-4459-a458-163dcb14ec56)
this is just a small part of the settings.
Hope it helps i didnt mean to be rude

**Comment by surfbryce** [comment]
@user-name-user So, the extensions thing is because I really just use the existing play-bar rather than creating a bunch of new stuff and having to update their state. Initially and up to this post I was ok with doing this because the only issues I was aware of were from themes and I could easily just patch those; but, I completely forgot about extensions adding stuff to it as well.

There have been many issues with using the play-bar for displaying all the informational content including the extensions issue as you mentioned so I've decided that I'm just going to go the route of creating all those elements myself and updating them appropriately. This will solve that issue as you mentioned.

For this extension though there will never be a customization menu for altering the appearance (for any part of the extension, Fullscreen is not exclusive here) - at least - not one planned for the time-being or foreseeable future. I take the Apple approach of designing a product where there is one design that generally works for everybody and looks great everywhere. Using the Spotify playbar and just rearranging its contents doesn't allow me to do this and actually design my own fullscreen information look. So with this change it will allow me to design the information section from the ground-up and experiment more appropriately.

If I do implement something to alter the appearance it will be similar to what Cinema mode has which is a button to toggle details and only keep the important information available (the playback state itself).

Going to move this to #188 since this post doesn't suggest anything and is more just criticism.
