### ISSUE TITLE
Full Screen resolution issue

### ISSUE THREAD

**Issue by sripushkar** [surfbryce/beautiful-lyrics#187]
Hello,

When viewing in full screen mode, the album art is of noticeably worse quality. I tried this on both my 4K monitor and MacBook and had the same issue; the "Full Screen" extension does not have this issue but then I cannot get the synced lyrics on that full screen view. I have attached an image of full screen with this extension vs another one; the difference in quality is very clear.
![Bad Quality](https://github.com/surfbryce/beautiful-lyrics/assets/34779754/4fb32ab7-483e-4d82-bb3c-0f29bb7bde19)
![Good Quality](https://github.com/surfbryce/beautiful-lyrics/assets/34779754/1c6ec364-973c-4514-9f42-b40acf1332ae)

**Comment by surfbryce** [comment]
@sripushkar Yeah this is a problem with using the Spotify playbar instead of creating all the elements from scratch is that the image won't update to use the higher resolution version so it still uses the lower-resolution one.

There are a number of issues that stem just from using the existing stuff so I'm just going to make a new issue marked as a feature where I make my own stuff to display all the information needed so I don't have to worry about this.

Although, to be fair, the Fullscreen App Display has a smaller cover-art preview so that's also to be taken into consideration. But also the playbar cover-art is the lowest resolution so that is just how it is.

**Comment by surfbryce** [comment]
@sripushkar Going to move this to #188, that'll be a better indicator for when this gets fixed and published.
