### ISSUE TITLE
How to activate everything

### ISSUE THREAD

**Issue by marceprz** [surfbryce/beautiful-lyrics#198]
so I have the beautiful lyrics but how do I activate the romanization and the rest of the things?

**Comment by Jfamig** [comment]
Wondering this too... How do I switch the kind of animation the text does??

**Comment by surfbryce** [comment]
@Jfamig The "animation" is based off the best synced version of the lyrics the extension can get (this is not performing the best right now which I am working on in the backend). In the future I will be adding how this works in the FAQ because a lot of people think that it's a setting that you can change but it's really a data thing. They will only be syllable, line, or statically synced based off what the artist/label submitted.

**Comment by surfbryce** [comment]
@marceprz Just look at the promotional material. I will probably have to add into FAQ on how Romanization pops up exactly. BUT Romanization will popup on any Japanese, Chinese, or Korean song that contains lyrics with those characters. It will appear in either the Fullscreen, Cinema, Page, or Card lyric-views as a button with a non-english character in it. You simply click that to romanize them.
