### ISSUE TITLE
(feature request) Embed into lyrics plus

### ISSUE THREAD

**Issue by RealLittlemrh** [surfbryce/beautiful-lyrics#201]
What I mean by this is to add this wonderful extension to lyrics plus so the karaoke on that works again and so then this extension would work with "Full App Display modified"

**Comment by surfbryce** [comment]
This is not planned at the moment. In the future there will be an API so that they can support my extension. However, the extension is currently not in a state where I would want other people to plug their stuff into mine. I want my extension to be relatively finished (which it is not) prior to me providing people the tools to use my extension in theirs.
