### ISSUE TITLE
hey the text doesnt seen to move as shown on the extension cover

### ISSUE THREAD

**Issue by Blacklight2k** [surfbryce/beautiful-lyrics#221]
1 pic here
![image](https://github.com/surfbryce/beautiful-lyrics/assets/153313149/b1bc6b61-4f1f-4156-a061-3a954e9a2d21)
it just fades in it doesnt move

**Comment by surfbryce** [comment]
@Blacklight2k I forgot to put this in the FAQ and I need to because people still don't know the difference between the different modes and how the lyrics move in the first place.

There are three modes:
- Static: Just plain text
- Line Synced: We have the start and end times for each line of text (which is what your image shows)
- Syllable Synced: We have the start and end times for each word/syllable (sometimes it can be a singular letter and other times it can be a whole word)

There is no setting becasue I don't process anything. All the lyrics that are retrieved and used are provided by the artist/label themselves.

So if line sync is given to you, that is the best version that the artist/label has provided. However, right now, there is an issue with my backend that gives the lyrics out where it's not getting anything from my providers. So it's completely possible you are seeing the line-synced lyrics that Spotify gives if you have Premium (unless you don't have Premium).

If you don't have Premium then that is the best version that exists syncing wise.

**Comment by Blacklight2k** [comment]
ok so if it is synced then the lyrics move up and down???

**Comment by surfbryce** [comment]
@Blacklight2k If the artist/label synced the song up so that it goes line by line lyrically then yes it will move the gradient Top to Down. If it is synced by word/syllable the gradient will go word to word or word to syllable and etc.

If it's not synced at all it'll just be a bunch of text.

**Comment by Blacklight2k** [comment]
ok tq
