### ISSUE TITLE
An option to choose where to use beautiful lyrics / configure size

### ISSUE THREAD

**Issue by Palka00** [surfbryce/beautiful-lyrics#229]
Hello. My idea is that I don't want to use beautiful lyrics in right panel because it's taking much space and using a lot of cpu. I'd like to keep it only in cinema mode. And the option to configure sidebar's lyrics size would be nice too.

**Comment by surfbryce** [comment]
Beautiful Lyrics is considered an "as-is" extension, performance is a big concern at the moment due to the graphics rendering being done and I'm working on optimizing that while not losing the look, but there will never be an option to choose where it's being used or an option to change the size of the lyrics.
