### ISSUE TITLE
Add Settings

### ISSUE THREAD

**Issue by Satanarious** [surfbryce/beautiful-lyrics#24]
Add an option to:
- Change the speed of the animation
- Toggle Lyrics Changes(Scrolling and Increasing Font-Size)

**Comment by surfbryce** [comment]
My main issue with settings - and this is my gripe with all extensions and Spicetify as a whole - is that every extension has it's own location for settings and their own way to get to that location.

I really don't like that reality for Spicetify or for my extension because it just adds a lot of complexity to something that should be simple (could argue that is what I am doing with this comment).

Currently - as the extension is - the only two settings I could provide are the background animation speed and font-size. Scrolling (whatever that means in particular) is not possible because that is Spotifys built-in implementation not mine.

But due to my prior stated reasoning I'm reluctant on adding settings to begin with.

Once I complete #15 and #14 I will reconsider this perspective. But as it stands I'm not considering adding settings - I see this extension as a visually finalized product - respective to its release.
