### ISSUE TITLE
Add menu.

### ISSUE THREAD

**Issue by ZoomMan2** [surfbryce/beautiful-lyrics#275]
Add menu like in lyrics plus to 

- on/off background animation
- Track delay
- lyrics animation styles
- lyrics alignments

**Comment by surfbryce** [comment]
Extension of #44 and #223

There is a common misunderstanding that the extension can switch between animation-styles as it pleases, but this is wrong, it has to be able to get the data to do that from somewhere, and that comes from the Artists/Record Companies. It's up to them to sync their songs lyrically so that companies like Musixmatch can provide me, Apple Music, Spotify, and etc. with those type of lyrics. If a song isn't syllable synced, or line synced, or has static text at all, that's because the Artists/Record Company chose to do that.

Alignments won't ever be an option because those are also decided by the lyrics.
