### ISSUE TITLE
Cinema mode needs an upgrade!?

### ISSUE THREAD

**Issue by js-16k** [surfbryce/beautiful-lyrics#297]
my guy made excellent extension for making experience these awesome lyrics.
Great work.
Just a teeny tiny issue that would increase my respect towards you is the cinema mode is not really fullscreen.
I downloaded multiple fullscreen extensions but all were supported only for lyrics-plus not yours truly beautiful lyrics.

If it's only me whose getting this issue let me explain by providing ref image:
![image_2024-02-22_172124944](https://github.com/surfbryce/beautiful-lyrics/assets/160855830/fb104f6e-db0d-4170-8754-a252aad31e58)

👆🏻Here you can see that i have not activated cinema mode yet and this is also not a bad experience hats off to your work.

But here👇🏻

![image](https://github.com/surfbryce/beautiful-lyrics/assets/160855830/ead8ac22-6e78-46f7-9fcb-e132ab10af52)
here you can see that i am in cinema mode now, romanization and all are excellent. It would be great if it was fullscreen. I really want fullscreen for your own lyrics. Please🙏🏻

I hate this one it is non customizable and too many playback controls for a fullscreen. Please make your own
![image](https://github.com/surfbryce/beautiful-lyrics/assets/160855830/327598e7-1461-4cc9-9f50-df2aeebcb361)

**Comment by thaddeuskkr** [comment]
> here you can see that i am in cinema mode now, romanization and all are excellent. It would be great if it was fullscreen. I really want fullscreen for your own lyrics. Please🙏🏻

if you're very desperate, a quick workaround for this would be to manually fullscreen spotify - but this requires you to enable devtools if you haven't already
```
spicetify enable-devtools
```

then you press `Ctrl + Shift + I` to open devtools, go to `Console` and use the following (if you're trying to copy/paste and it doesn't allow pasting, just type `allow pasting` and press enter):
```js
document.body.requestFullscreen() // to go into fullscreen
document.exitFullscreen() // to exit fullscreen
```

**Comment by surfbryce** [comment]
@js-16k The customization aspect will never be a thing, I've explained why in #44. However, if you want to make another Issue and have it be about collapsing the fullscreen view elements into a small card in the top left or something I would gladly mark it as a suggestion and have that planned for a future update.

As for making my own custom elements rather than reusing Spotifys existing elements, I already have that planned in #188.

So going to close this as it doesn't add anything that hasn't already been discussed.
