### ISSUE TITLE
Dumping RAW lyric files

### ISSUE THREAD

**Issue by sortedcord** [surfbryce/beautiful-lyrics#301]
Hi, I just came across this extension and I'm quite impressed by how much it overhauls things. I'm working on a music player and would like to implement a similar word-by-word/syllable-by-syllable live lyrics. Would it be possible to dump the raw lyrics as it so that I could see how exactly are the timestamps parsed?

**Comment by surfbryce** [comment]
@sortedcord I'm not sure what you mean by "dump", but there's an open-sourced project called Lyrics Plus which would be perfect for you to look into, they have all the parsing client-side over there (since they retrieve from public uncontrolled endpoints like Musixmatch).

I don't handle/store files though, so there wouldn't be much to dump other than what is being provided by my endpoint. If you were asking for the raw information, there is not a way to get the raw unparsed lyrics and there isn't a plan to make that an option (for obvious reasons),

**Comment by sortedcord** [comment]
Oh, I thought you were somehow modifying the api calls to musixmatch for the lyrics, if not, then what provider are you using that has all these features (if you don't mind answering)?
