### ISSUE TITLE
lyrics not in sync with song audio

### ISSUE THREAD

**Issue by mcwick002** [surfbryce/beautiful-lyrics#302]
https://github.com/surfbryce/beautiful-lyrics/assets/161468014/c6572f0c-4cef-40db-9991-18a86e059777

the only song that ive encountered which isnt in snyc, tried to reset spotify and redownload beautiful lyrics the issue still persists.

**Comment by riivx** [comment]
i think it's pretty obvious that you shouldn't report it here. every lyric issue should go to lyrics provider which is either musixmatch or spotify directly

**Comment by surfbryce** [comment]
@riivx Not true at all. I heavily prefer that lyric issues be brought up here in GitHub so that I can check that it is not an issue on my end when doing the lyric retrieval. It's not always Musixmatch or Spotifys fault.

I haven't checked what's being parsed and where this information is being grabbed from yet, so it's entirely possible it's a problem on my end.

Will get back to this when I have the time to check why it's specifically doing this

**Comment by mcwick002** [comment]
> i think it's pretty obvious that you shouldn't report it here. every lyric issue should go to lyrics provider which is either musixmatch or spotify

**Comment by mcwick002** [comment]
> i think it's pretty obvious that you shouldn't report it here. every lyric issue should go to lyrics provider which is either musixmatch or spotify directly

i mean spotify's own lyrics work fine, no desync

**Comment by EnderPoint07** [comment]
same thing on https://open.spotify.com/track/67hbP9PFQZrb4XZc3TzB0s?si=89b0227e27254bef

**Comment by EnderPoint07** [comment]
i would suggest a way to offset/delay or undelay(idk the word) the lyrics. pretty sure there is a similar feature in lyrics-plus mod.

**Comment by surfbryce** [comment]
@EnderPoint07 Not going to do that. That is not a good solution at all for a problem which can be fixed statically (rather than relying on the user to fix it). I haven't looked into checking what the options are for this song, but I've described in other issues (and in the most recent release) that I'm going to look into a method that makes it so my service gets all the Spotify information (rather than you, the client) so that it can accurately find the best match to reduce syncing concerns.

This is not really an available lyrics problem, this is more or so trying to find the best equivalent lyrics to the song. It's a difficult problem to solve because you can't just go and find the exact version that matches, you have to do a little bit of handling to find the best one.

**Comment by EnderPoint07** [comment]
@surfbryce
you have a point regarding it not being the most optimal solution for the user but i still believe it to be a nice QoL feature in the edge cases where the algorithm is giving incorrect lyric timings. In those cases the user would be able to fix that themselves with not that much difficulty. It is practically impossible to have such perfect handling of the lyrics that its going to be correct 100% of the time and hence i believe the best way to solve that would be allowing the user to offset the values themselves. Human judgement for the timing is always going to be better or atleast tolerable than any other algorithm i can think off. Ofcourse this is my opinion only with assumptions on how the extension works.

Thanks,

**Comment by surfbryce** [comment]
@EnderPoint07 Well, this is what I have to say just in general.

There will be a universal delay feature added, but not for lyric sync correction, but for bluetooth devices where there is a delay in transmissions/playback. There was a feature request for that made, so that will be the only reason why I add delay.

With the adjustments I plan on making for the lyrics, it should eliminate most (if not all) syncing issues with lyrics because I'll have direct access to the track length and more on the server-side (which I do not have at the moment).

Sometime this year, probably summer, there will be a lyrics editor that people can use to make their own lyrics or edit existing lyrics. So I plan for this to be the main way so the community can create/correct lyrics for songs so that everybody can have a better experience.

**Comment by EnderPoint07** [comment]
> With the adjustments I plan on making for the lyrics, it should eliminate most (if not all) syncing issues with lyrics because I'll have direct access to the track length and more on the server-side (which I do not have at the moment).

Any chance your backend is/planned to be open-sourced?  It would be interesting to know how the lyrics are being retrieved and parsed. 

> Sometime this year, probably summer, there will be a lyrics editor that people can use to make their own lyrics or edit existing lyrics. So I plan for this to be the main way so the community can create/correct lyrics for songs so that everybody can have a better experience.

A community based lyrics system would work in theory but then u got to take into account trolls and stuff, and for a similar way to how wikipedia does it, you would need pretty large community base with dedicated mods. Anyways goodluck and epic work btw.

**Comment by surfbryce** [comment]
@EnderPoint07 Backend will be open-sourced once I consider it stable/ready for others, will most likely be open-sourced once the lyrics editor is done.

As for the lyrics-editor, I've already fleshed out how it'll work from the social to technical aspects. A lot of what you brought up isn't much of a concern and you don't need that many moderators, people can submit lyric revisions or new lyrics which will be automatically applied for them locally, and if approved by somebody, then applied for everybody else as well.

Wikipedia is vastly different because when information is added you have to verify that information is correct and that the sources cited are also valid. With the lyrics editor, the moderators are able to listen to the song alongside looking at the submitted lyrics, so there's not much work other than seeing if the lyrics are properly synced and that the words match.

Arguably, the issue for moderation is languages which people doing the moderation do not speak. But nothing a simple google search for the existing text lyrics can't solve.

I appreciate the concerns however, valid points to bring up!

**Comment by surfbryce** [comment]
Should be fixed in latest update, re-create the issue if it still happens
