### ISSUE TITLE
8-bit vs. 10-bit Dynamic Backgroud

### ISSUE THREAD

**Issue by Ender-Wang** [surfbryce/beautiful-lyrics#313]
I noticed that there's a color continuity problem/flaw in the dynamic background, I assume the dynamic background is in 8-bit depth, cause 10-bit depth would not have that kind of issue. So I am asking if it's possible to generate 10-bit images for the dynamic background instead of appers-like 8-bit. Besides, consider the G/CPU consumption, how does it compare to 10-bit? If it's like a ~5% increase, I won't mind. Btw, it's kinda obvious on a 28" 4K display, but it's not that eye-catching on the default 14" display of my MacBook.

**Comment by surfbryce** [comment]
@Ender-Wang The dynamic background is simply done using images and CSS, there's no programmatic background. So whatever bit-depth the images provided by Spotify are in is what you are going to get. There would be no way for me to change the bit-depth in the first place.

Another thing I want to point out is that I use an Ultrawide QD-OLED 4k 10bit depth display, so I'm not really sure what you are talking about specifically. Your mention of a "color continuity problem/flaw" means nothing, those words hold no value because there's nothing to visually demonstrate what you are talking about. If you had explained the problem more technically (rather than generic layman's terms that could mean anything) it would be easier to understand what you are experiencing.

I also want to add an additional mention, in combination with my QD-OLED display I also use a 2021 M1 Pro Macbook as my secondary display. I often develop with Spotify on that display and my code on my main QD-OLED Display. I test Spotify on both monitors as well. I will admit I have calibrated my QD-OLED to be completely color accurate using professional tooling, but that shouldn't affect the outcome you are describing.
