### ISSUE TITLE
Unable to develop due to breaking dependencies

### ISSUE THREAD

**Issue by DannyDelic** [surfbryce/beautiful-lyrics#321]
First off, for a 1-man open-source job, the repo is thoroughly documented. Kudos here, this is really well-done craftmanship.

Now, outdated dependencies (presumably this repo mainly, https://github.com/surfbryce/spicetify-packages, some types no longer being present) make it impossible to compile the project, so iterating inside Spotify is quite hard.

I would like to open a PR for customizing certain styling elements, in particular adding sliders for strength of the live background, the gradients/highlighting around the vocals and the edge blur in the lyrics view. Then you can just grab whatever part of the logic you are interested in, if it fits inside your vision for the project.

Types of compile errors in question:

1. `error TS2307: Cannot find module '../../Packages/Schedulers/Scheduler' or its corresponding type declarations.`
Presumably due to above mentioned packages project being out of date.
2. `Cannot find module '../../../../Shared/Lyrics' or its corresponding type declarations.` A new Shared directory, that I could not locate anywhere in your repos.
3. `src/Modules/LyricsViews/Components/PageView.ts:12:10 - error TS2305: Module '"../../../Services/Player/LyricsUtilities"' has no exported member 'ParsedLyrics'.` Certain types from the services directory are referenced, but I could not find any existence of them - so I assume you have done some refactors elsewhere.

**Comment by surfbryce** [comment]
@DannyDelic I appreciate the kind words.

There are few major changes coming this month (more or so related to lyrics fetching) which I would wait for in terms of PR'ing.

Now the main repo right now actually doesn't represent the distributed/packaged version, I mainly made the mistake of making a large lyrics rewrite in the main local repo rather than making another branch dedicated to it. So that might be why the repo may not run using the build/test commands.

I'll probably end up moving these packages into the Beautiful Lyrics repo since I just found out you can link repos apparently on GitHub (so the Spicetify-Packages Repo will just be links to the Beautiful Lyrics files or it'll be vice-versa, not sure), I'll have to find out how that whole thing works.

You should see all of this fixed and useable again from an external development standpoint once the new lyrics improvements come this month.

Also on the basis of what your PR would introduce, I am typically very against customization options due the lack of a standardized customization workflow in the Spicetify ecosystem (causing every extension to have its own nuanced way of customization that is confusing). So it is unlikely that I would add in customization options like the ones you are proposing, but, if you manage to do them in a very easy and attractive manner I may consider them.

**Comment by DannyDelic** [comment]
That makes sense, I am new to the spicetify eco-system - I had also assumed that the actual user-facing implementation would be the most difficult part, hence why I just suggested you should grab the logic part (although that is quite trivial).

I will keep an eye on the repo until then, and in the meanwhile I will consider what might be the most seamless implementation within your vision.

**Comment by surfbryce** [comment]
Going to close this for now since it should be resolved soon and isn't technically a bug/issue with the extension itself

**Comment by ziIIas** [comment]
Hey, any updates on this? I was gonna try to fork for personal use this to implement Genius as a third lyric provider, mainly for tagged local files (as they don't have ISRC codes) and if successful would PR it if you are interested. +1 on documentation btw 😀
