### ISSUE TITLE
Theme Dribbblish purple Issues

### ISSUE THREAD

**Issue by Roxo7777** [surfbryce/beautiful-lyrics#329]
![Captura de tela 2024-03-21 215752](https://github.com/surfbryce/beautiful-lyrics/assets/85604299/d1458a05-039a-42e6-8b14-5ed50d931d5c)

**Comment by surfbryce** [comment]
@Roxo7777 What's the issue?

**Comment by virtualgurel** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/113795958/dd3b4af7-f922-44be-97a5-99947a389047)

Probably talking about the sidebar. Beautiful Lyrics changes the sidebar background so it's not looking nice. An option to toggle the sidebar background color would be a nice addition. BUT more importantly, my dribblish purple theme looks nice. So it could be a local bug.

**Comment by surfbryce** [comment]
@virtualgurel I was figuring but the whole point of the extension is to modify these elements and it is advertised so it made no sense to me that somebody would report that as a bug.

As for your case it is because #441, going to close this since it's been forever and they've had the opportunity to respond
