### ISSUE TITLE
Synced with apple music but not Spotify

### ISSUE THREAD

**Issue by LoganWolfie** [surfbryce/beautiful-lyrics#337]
Apple music is like instant with beautiful Lyrics but for spotify it takes time. Are they using the same thing or not? 
I mean they can't look any more similar then they already do it's practiacally 1:1 it's just that this mod for spotify takes a long time to update new songs when Apple music just has it instantly.

That's of course unless they're not using the same program to set it up and they're not related at all but I mean they look Identecial.

Also Musixmatch already has it synced and im guessing this takes from Musixmatch but it's still not updated for this plugin yet.

![image](https://github.com/surfbryce/beautiful-lyrics/assets/72407034/991d47fa-f297-4dd8-bf27-7792b3df8b07)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/72407034/a8d9b471-8d83-4399-8c74-8e3eeebc7397)

**Comment by Zyanbob** [comment]
is anyone going to tell him that apple music's lyrics are internally made by apple and that beautiful lyrics only works on Spotify desktop?

**Comment by LoganWolfie** [comment]
Yeah Im just saying that if Musixmatch is updated almost instatly how come beautiful lyrics takes weeks to update?

**Comment by surfbryce** [comment]
@LoganWolfie It's probably more that my backend isn't finding the right song for it because its strictly relying on the ISRC, this will change sometime this month where it doesn't rely on just the record-code.

The main thing people don't know is that Spotify/Apple Music tend to have different versions of the same song, so the lyrics can't match up 1:1 when you just using their record code, you have to use more information.

Since we have eyes we can tell they're the same, but a computer can't do that so easily with just one piece of information.
