### ISSUE TITLE
Roughly half second delay on new verse scroll

### ISSUE THREAD

**Issue by Ridley-nelson17** [surfbryce/beautiful-lyrics#36]
I'm creating this issue as I haven't yet gone over the source code, but I can tell you I'm running a Surface Pro 7+ and computing power shouldn't be the problem. On every other new "line" it fails to scroll correctly to the correct line height. However, it does correct itself within a second.

**Comment by Ridley-nelson17** [comment]
should've mentioned this is using the most recent version of Spotify/Spicetify for windows 11 (x64). I'll review the source code later and probably reply here with a solution.

**Comment by surfbryce** [comment]
> should've mentioned this is using the most recent version of Spotify/Spicetify for windows 11 (x64). I'll review the source code later and probably reply here with a solution.

You won't find anything because..... there's no custom scrolling implementation. I don't advertise anywhere that there is - if there was it would definitely be good for promotion.

What's occurring is due to how Spotify does their scrolling. They don't adapt to lyric-text size changes - which - I am changing when the active text class is applied.

I've explained when this will be fixed by me and how in issue #9 . In reference to the topic, this post is a duplicate so I'll be closing this.

However, if you find a way to prevent Spotify from doing this somehow - feel free to make a Pull-Request; I'll review it and then publish it if there are no issues with it.
