### ISSUE TITLE
[Suggestion] Use QQMusic as a backup if Apple Music doesn't have real-time lyrics 

### ISSUE THREAD

**Issue by Marmur2020** [surfbryce/beautiful-lyrics#366]
I like the fact that Lyricify uses QQ music because it has no problems. Apple music depends on the author added word support or not and it happens that the author made animation not with words, but with a line. At QQ is independent or not they try to make animation with words (I have not seen that the text animated by a line or no text at all).

QQ music that uses Lyricify: https://github.com/WXRIW/Lyricify-Lyrics-Helper/blob/master/Lyricify.Lyrics.Helper/Providers/Web/QQMusic/Api.cs

**DISCLAIMER:** It is recommended to use QQ music in extreme cases if there is no song in Apple music or it is not animated word for word!

**Comment by surfbryce** [comment]
@Marmur2020 QQ is very very hit or miss, sometimes you can get completely wrong lyrics or lyrics for an english song in a different language. I don’t even use Spotify static lyrics because they also can be completely wrong for a song, sometimes giving lyrics from another song to an instrumental!

So this won’t ever happen, sorry!
