### ISSUE TITLE
(Suggestion) Animated Lyrics Video

### ISSUE THREAD

**Issue by CodedNil** [surfbryce/beautiful-lyrics#38]
Would it be possible to replace the albums art in the lyrics sidebar with animated canvas like this:
https://github.com/itsmeow/Spicetify-Canvas

I feel like it fits the style of this plugin with the moving background, same as the mobile app does

**Comment by surfbryce** [comment]
This is something I've been suggested before in the Spicetify discord and I did have a plan to work on this eventually at one point since the API internally exists to retrieve these easily.

The main thing I would have to work on is figuring out how to properly integrate this so it works well with the custom background. I don't want to straight up replace the album-art because a lot of brands will use the same animated-background for a wide-range of songs across several album covers (The Beach Boys for ex.).

So ideally it would be some way to blend it with my animated background and theirs.

**Comment by newBonfire** [comment]
This feature would be awesome, I'm sure it would be loved by the community. Also integrating this extension with full Screen extension and lyrics plus is something I'd love to see.
Thanks for the beautiful extension.

**Comment by surfbryce** [comment]
@CodedNil @cariosa This is actually now supported, if you turn on canvas within Experimental Features it will look great!
