### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by dksucker** [surfbryce/beautiful-lyrics#40]
hey i have tried to install the extenstion through marketplace but didnot work although spicetify and spotify up to date and i have tired to download it manually and didnot work either so i dont know where is the problem

**Comment by surfbryce** [comment]
Can you explain what specifically isn't working? A little more information would be awesome!

**Comment by dksucker** [comment]
sorry my bad the beautiful lyrics extenstion is not working  with me and i have listed above everything else

**Comment by 404Mohammed** [comment]
the background doesnot show like it is in the preview it is just like i didnot install it

**Comment by surfbryce** [comment]
> the background doesnot show like it is in the preview it is just like i didnot install it

can you send me a screenshot of your Spotify/Spicetify version?

You can do that on windows by right clicking the top bar and pressing "About Spotify" and you can do that on MacOS by doing "Spotify -> About Spotify".

Can you also tell me if you are on Windows or MacOS?

**Comment by 404Mohammed** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/138071392/4e9c03d0-2ad0-4be9-9bad-082092e8be80)
iam on windows 11 and sorry i cant seem to find about spotify thing but i have recently downloaded it 1hour ago

**Comment by surfbryce** [comment]
> ![image](https://user-images.githubusercontent.com/138071392/249644412-4e9c03d0-2ad0-4be9-9bad-082092e8be80.png) iam on windows 11 and sorry i cant seem to find about spotify thing but i have recently downloaded it 1hour ago

Sorry I misspoke, I don't use Windows so I get it confused sometimes.

<img width="717" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/6d3da606-cc45-4e7b-9364-d844ea00f725">

If you click on those three dots (ellipses) the context-menu with that option I mentioned should appear

**Comment by 404Mohammed** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/138071392/e206e3b3-bea6-4bfa-ad5c-0703815e041c)

**Comment by surfbryce** [comment]
@404Mohammed Yeah that's correct - I apologize for responding so late. I've been awfully busy since then (and was at the time of responding).

You are on the same versions that I am except the only difference is that you are on a 32bit version. Not sure if it's a limitation on Spotifys end or not.

I'm pushing out a big update this Friday/Saturday (haven't decided when yet) so if it's not fixed then I will have to take a look on a windows machine to see if its platform dependent.

**Comment by 404Mohammed** [comment]
sure no problem i will be waiting for the update when it drops i will notify you if it is working btw i have searched online and there is no 64 bit version for windows

**Comment by surfbryce** [comment]
@404Mohammed Ah my bad, I never checked that panel on Windows so had no idea - just figured it would've been built for 64bit if possible. Thanks for the clarification!

**Comment by 404Mohammed** [comment]
That is okay no problem hope your update fix the issue because i found it common with my friends with windows 11                by the way something i found out that may help i live in Egypt and there was recently internet restrictions happend in the country so in order to extensions  to work i would have to install them manually through powershell and all that stuff (but thems works just fine i dont know why it is only the extensions that do that) hope that may help and thank you so much

**Comment by surfbryce** [comment]
> @surfbryce That is okay no problem hope your update fix the issue because i found it common with my friends with windows 11 by the way something i found out that may help i live in Egypt and there was recently internet restrictions happend in the country so in order to extensions to work i would have to install them manually through powershell and all that stuff (but thems works just fine i dont know why it is only the extensions that do that) hope that may help and thank you so much

Actually this is a very good point - in the Spicetify discord I have heard of people not being able to access JSDelivr (The website that Spicetify uses to get extension code) because their country blocked it.

Even searched it up for Egypt and got this immediately lol;
<img width="624" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/4d36a0ef-9162-4ce4-ab56-82d9cdf2023f">

So, there's one to make sure that this is the case - follow these instructions;
1. Open your command prompt and type in "spicetify apply enable-devtools"
2. Then click on the three dots in the top left and click develop
3. Then click developer tools
4. Go to the console tab and screenshot everything you can from it.

This will help us determine if its JSDelivr being blocked being the issue or if my extension may have thrown an error out. Thanks so much btw! I should mention this on the FAQ if this ends up being a country issue

**Comment by 404Mohammed** [comment]
@surfbryce thanks for the info i knew that the country blocked something but didnot know what is it i will try to see a fix for jsdeliver anyway is the screen you are asking about?
![image](https://github.com/surfbryce/beautiful-lyrics/assets/138071392/c6c605cf-05dd-452d-b3c4-7c435b10bb2d)

**Comment by surfbryce** [comment]
> @surfbryce thanks for the info i knew that the country blocked something but didnot know what is it i will try to see a fix for jsdeliver anyway is the screen you are asking about? ![image](https://user-images.githubusercontent.com/138071392/250203561-c6c605cf-05dd-452d-b3c4-7c435b10bb2d.png)

yep! that's perfect, I'm assuming this JSDelivr request that resulted in a 403 (forbidden) is the request marketplace made for my extension

<img width="1584" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/5cdae125-9c55-4a45-97ab-1e50f449051a">

can you right click on that link I pointed to and copy and paste it here?

**Comment by 404Mohammed** [comment]
@surfbryce  okay there it is  https://cdn.jsdelivr.net/gh/spicetify/spicetify-themes@master/Default/user.css?time=1688161272890

**Comment by 7osssam** [comment]
I got the same problem (live in Egypt too 🧑🏽‍💻💀)

**Comment by 404Mohammed** [comment]
@surfbryce  Hi just wanted to tell you that the extension is now working after your update thank you for your hard work hope you good <3
