### ISSUE TITLE
no "beautiful-lyrics-main.js" found in the folder

### ISSUE THREAD

**Issue by avitchese** [surfbryce/beautiful-lyrics#405]
hi, i'm new, and english isn't my native language so i'm sorry if u cant understand me completly, also i don't know how to use powershell or do these smart things that y'all do.
please help me and explain to me in the most easiest way, to a dumb person like me.

**Comment by surfbryce** [comment]
@avitchese I only really advocate for things to be installed via Marketplace, I don't really provide instructions on how to install locally because of how much of a pain it is.

I think if you download the file in the "dist" folder, move it to some location on your computer that Spicetify has access to (check the official website for more information on that) and run "spicetify config extensions beautiful-lyrics.js" it should work!

Not going to be able to help much further than that, sorry!
