### ISSUE TITLE
[IDEA] Add custom lyrics

### ISSUE THREAD

**Issue by Max87153** [surfbryce/beautiful-lyrics#445]
There's some songs that do not have any lyrics at all, or aren't actually displayed. It would be cool to make a button to locally add the lyrics to a song, it doesnt have to have that beautiful page with the lyrics moving (would be hard to code) but just so you can read them.

**Comment by Some1sm** [comment]
Imagine an extension that added speech to text with AI and synced them automatically lol

**Comment by surfbryce** [comment]
@Max87153 There is a Lyrics Editor planned to be worked on and finished sometime in Summer, this will allow for community backed Lyrics.

So there won't be anything until then, when I put in features I want to do them right and not cut corners, so in this case a fully featured lyrics editor is doing it right, anything less is cutting corners.

Also @Some1sm, having an AI within Spotify itself won't be possible for an extension, having it externally would work but the problem is that you need an AI that works with all possible languages for it to be worthwhile, which just isn't possible at the moment. I've thought about making an AI just to sync up human written text with the song but the problem is you also need the audio, which just isn't possible to get on Spotify legally.
