### ISSUE TITLE
Occasional splitting of whole words

### ISSUE THREAD

**Issue by Avenred** [surfbryce/beautiful-lyrics#45]
Occasionally, better lyrics will split a word in two (e
nough)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/13921970/4b56186e-03d0-41ac-99e1-119ea6a75b1e)

You can reproduce by making the width of the window just small enough. Song in the screenshot is Where You Are by John Summit

**Comment by surfbryce** [comment]
Ah this is a bug I forgot to fix - basically what's happening here is that some songs have words that are split into parts (so that their time-progress can be different per parts of the word) - and I do support these but I don't lump them together into a "word-group" and so when everything renders it'll wrap parts of the word if it doesn't all fit.

This is a relatively easy fix so you should see an update popup soon.

**Comment by surfbryce** [comment]
This is now fixed. The extension should auto-update!

<img width="264" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/ab69f7e6-1d5d-44a7-9506-48bbefb6fc00">
