### ISSUE TITLE
When is update coming out

### ISSUE THREAD

**Issue by HummerBlaster** [surfbryce/beautiful-lyrics#460]
Not to be rude but everytime you say “ its coming on may 1st “ or “ its coming today “ you just never release it. Please don’t take this the wrong way but we really like your project that is why we are asking like this. Please could you give us an exact time like you specified that it will be on friday ABSOLUTELY. By friday do you mean today or next friday?

**Comment by surfbryce** [comment]
That's the life of a solo developer, unexpected delays and you're the only one who can do things about it; I meant May 3rd, as in today, but because I'm in PST it'll most likely come out May 4th for a majority of people. I've updated the newest post I made to clarify on that, since you're not the only one who got confused by it
