### ISSUE TITLE
Suggestion for switching different full screens Interface

### ISSUE THREAD

**Issue by aneesh1122** [surfbryce/beautiful-lyrics#505]
When we are in the true full screen mode, pressing `Esc` takes us to Cinema mode(Full windowed lyrics+Windows Taskbar)

Could you please assign `Shift + Esc` in true full screen mode to `Exit Cinema`? That would be very useful.

Also, I found some Typos
![2024-05-16 12_46_08-Greenshot](https://github.com/surfbryce/beautiful-lyrics/assets/45353488/f38c7a47-c1d2-4fcd-a206-8f64b1f25593)
![2024-05-16 12_46_12-Greenshot](https://github.com/surfbryce/beautiful-lyrics/assets/45353488/fc0a73b3-34fc-4345-8bf1-da7154e154e7)
Both of them shows "Exit Fullscreen"

The first one should show "Enter Cinema Mode"

**Comment by surfbryce** [comment]
@aneesh1122 Alright so I've made changes to the cover-art icons.

I've also added escape-key support, so when you enter fullscreen from the playbar icon, and press escape, it will fully close out that view. BUT, if you enter fullscreen from the Cinema view, and then press escape, it'll go back to the Cinema view.

I believe this would be the expected behavior, that if you enter fullscreen from the playbar you expect pressing "Escape" to exit out of it, but if you enter Fullscreen from Cinema you would expect it to go back to Cinema view (unfullscreening).

This will be available in the next patch

**Comment by aneesh1122** [comment]
> @aneesh1122 Alright so I've made changes to the cover-art icons.
> 
> I've also added escape-key support, so when you enter fullscreen from the playbar icon, and press escape, it will fully close out that view. BUT, if you enter fullscreen from the Cinema view, and then press escape, it'll go back to the Cinema view.
> 
> I believe this would be the expected behavior, that if you enter fullscreen from the playbar you expect pressing "Escape" to exit out of it, but if you enter Fullscreen from Cinema you would expect it to go back to Cinema view (unfullscreening).
> 
> This will be available in the next patch

Thanks man
