### ISSUE TITLE
Every word gets stuck for less than a second only in Lyrics Page

### ISSUE THREAD

**Issue by rawniee** [surfbryce/beautiful-lyrics#537]
A word is half completed and then the word's sync gets stopped for a very short time which hampers the overall smoothness of the entire lyrics. I first thought it was only an issue from my end but in the sidebar and full screen the words aren't getting stuck. I have hardware acceleration enabled as well. Hope this gets looked into!

**Comment by surfbryce** [comment]
@rawniee Made a change in the last update so that's probably why, the implementation was based on the presumption that the transport between Spotifys C++ side and its Browser side was almost instant; but based on some bug reports it seems like that isn't the case. So I'll make a change to update how that works.

**Comment by surfbryce** [comment]
@rawniee Alright this should be significantly better in the next patch. The timestamp is now incremented on every frame and syncing updates are done IF needed
