### ISSUE TITLE
Please make beautiful lyrics prioritize non-romanized versions of songs

### ISSUE THREAD

**Issue by NAXRAY** [surfbryce/beautiful-lyrics#538]
Hello, after the new update beautiful lyrics is getting romanized lyrics for songs. An example below, before the update beautiful lyrics used to have the same as the spotify lyrics:

SWITCHIN LANES' by Tegi Pannu
![image](https://github.com/surfbryce/beautiful-lyrics/assets/94483984/51ea8c75-a1dd-4fc8-a4cd-7412b4a1f278)

Now it is getting romanized lyrics instead

![image](https://github.com/surfbryce/beautiful-lyrics/assets/94483984/7d3fe150-1091-45f2-935d-2c3fafa3a965)

**Comment by surfbryce** [comment]
I'll check this out, it should be getting it in the native language, but also there wouldn't be a way to determine if something is non-romanized or not. But this should be a different issue entirely, so I'll check it out

**Comment by surfbryce** [comment]
@NAXRAY Unfortunately, Apple Music only has this romanized version for some reason. Don't think there is anything I can really do here, eventually when Musixmatch is supported, it will be able to grab those line sync lyrics instead. For now, I can't do much.

**Comment by NAXRAY** [comment]
Ooh okay thanks for the information. I did notice that some other songs are identical to the Musixmatch lyrics on the plug-in as well, which is why I thought the plug in also used Musixmatch. Is that instead because Apple Music takes lyrics from Musixmatch as well and it just isn't taking it from Musixmatch for this particular song?

**Comment by surfbryce** [comment]
@NAXRAY I'm not really sure why Apple Music doesn't have the proper lyrics here, there are really only two possibilities here:
1. These are the lyrics that Musixmatch had at one point, and Apple Music just hasn't updated what they got from Musixmatch since then
2. The label/artist submitted these lyrics directly to Apply Music (which takes precedent over Musixmatch)

I honestly wouldn't be surprised if it was the first option to be fair; anyways, in the future Musixmatch will be used to cover for some songs that don't have the best options available.
