### ISSUE TITLE
how do i change beautiful lyrics settings?

### ISSUE THREAD

**Issue by ooogerman** [surfbryce/beautiful-lyrics#545]
my side panel now has album blur and its disgusting

**Comment by IamFastre** [comment]
how dare you say that, sir!

**Comment by surfbryce** [comment]
@ooogerman Bro how can you complain about something that was obviously advertised LMFAO, no there are no settings and there never will be, it's a come as it is product

**Comment by ooogerman** [comment]
I literally did not ask for that feature tho. I should have an option for that, it’s unfortunate because you somehow ruined the extension more than it already was ruined, it’s completely unfair that you don’t even let us have an option to change it, you were the only one bitching about realising all these different changes and you obviously couldn’t handle it, it’s fucking annoying cuz nobody asked to be forced to wait 3 months for a shitty update with features that same don’t like and have no option to change

**Comment by IamFastre** [comment]
dude, it's a free extension, you weren't forced to wait 3 months, you're being quite mean for someone making a free service
and the decision of whether to make it customizable or not is his decision, and as far as I can tell the extension is open source and nothing is stopping you from forking/modifying it yourself
relax

**Comment by ooogerman** [comment]
Idfc if im mean? That is such a stupid choice, the one thing the extensions has is the people who use it and not giving easy Customisability to the people who use it is so stupid, not everyone likes the blur thing and it fucks up listening to local files with no cover it would be understandably if there was an in client option to change it but she just said “bruh no”  it’s actually so fucking stupid and can ruin the whole layout of spicetift for the poor people who have to deal with this ignorant ass shit who don’t want to have it and don’t understand the likes of forking, or how to even modify open source projects for themselves

**Comment by surfbryce** [comment]
@ooogerman Then why did you install the extension? It wasn’t added, it has always been in the extension since the beginning. There was a bug that prevented it from being shown, I fixed it, nothing was added. For over a year (prior to you using my extension) people installed it for that plus more.

You need better opinions that are more inline with reality, like I said, the extension ADVERTISED that feature, you chose to install it. Not my fault you think a feature that was advertised since the start is something I just added.

**Comment by ooogerman** [comment]
Idk bruh I think maybe just maybe people install your extension because of how you lyrics work and not the blur but idk

**Comment by surfbryce** [comment]
@ooogerman Well for almost half a year they were installing it for the background since that is all it did before I even did lyrics. And before not even doing any research and looking like a total asshat, you might want to check the existing issues like #157, which somehow I remembered and I only see it like three times a year.

It’s not “disgusting”, and 99% think it looks good, you’re one of few that have that opinion, if your reason was “it clashes with my theme” that would’ve been fine, but you went personal and made yourself look stupid.

**Comment by ooogerman** [comment]
Are you actually fucking stupid? Like genuinely in what stupid part of your brain makes you think the fact that them downloading an extension that changes the side panel has anything to do with beautiful lyrics if that’s what it was before you did anything with lyrics you fucking moron

**Comment by surfbryce** [comment]
@ooogerman I don't know how you are this dense or even found a way to make a GitHub account.

Beautiful Lyrics was originally an extension made to add that background to the side-panel, that is what people were installing it for in the beginning! So in fact, it has EVERYTHING to do with Beautiful Lyrics (because that was the feature that started it and has been in it ever since). Like I said, the more that you comment, the more you expose your lack of intelligence.

You ignore my other points because you know I'm right, or you are incapable of reading beyond what agitates you. Either way, I'll take my rest from this, like I said earlier; #157 already exists, you can show your support there. I don't owe you anything and I am unbelievably thankful for it.

**Comment by ooogerman** [comment]
You might actually be retarded holy shit
