### ISSUE TITLE
Missing lyrics in the Korean song and other

### ISSUE THREAD

**Issue by Blankk02** [surfbryce/beautiful-lyrics#55]
![2023 07 04 TbY](https://github.com/surfbryce/beautiful-lyrics/assets/67868803/2479659d-b574-427b-b02a-434a9fd58268)

**Comment by Blankk02** [comment]
And I also noticed that it can happen that there are no lyrics in the spotify, but because of this extension the lyrics are there

**Comment by surfbryce** [comment]
> ![2023 07 04 TbY](https://user-images.githubusercontent.com/67868803/250699853-2479659d-b574-427b-b02a-434a9fd58268.png)

Huh, that's super weird - I originally saw this notification on my watch and thought they were static lyrics (which I do not use from Spotify).

But since they're line-synced that's obviously not the case so I'll take a look at that immediately, thank you!

**Comment by surfbryce** [comment]
Alright so this is going to require some extra work from me in regards to Lyrics. Right now I handle Spotify lyrics on my backend side but I think I'm just going to have to move this to the front-end (extension side).

What I'm assuming is happening is that certain lyrics become available in certain regions first and then others later - and so because the backend is using U.S. it's not able to access those lyrics yet.

This is what it looks like for me;
<img width="1722" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/5e031378-a649-4b2f-b3bf-0f4edea17670">

So, realistically I'll just have to do it that way since it's the only way to solve this (and it'll take a lot of load off my backend as well).

**Comment by UniFio2475** [comment]
And also for some song it does the lyrics like spotify but don't sync with the music, things that work well without the extension.
1. without the extension
2. with the extension
![image](https://github.com/surfbryce/beautiful-lyrics/assets/113627310/19753c50-a10f-4f0f-99e0-4ba483dc270f)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/113627310/6a8ed17e-92ad-495e-90ac-bda3db1e6225)

**Comment by Blankk02** [comment]
@UniFio2475 Also, now I don't have the lyrics for some reason, but they remain on the songs he worked on
I also noticed that in one song there is no lyrics in the spotify, but there is with this extension and the lyrics go and do not stand

**Comment by surfbryce** [comment]
Alright I just made it so that Spotify lyric-fetching is done on the client-side so that any requests made for lyrics from Spotify are done from your end. This should fix these problems - if you are still having issues please don't hesitate to comment here and I will reopen this issue!
