### ISSUE TITLE
Fullscreen Redesign

### ISSUE THREAD

**Issue by sealants** [surfbryce/beautiful-lyrics#57]
I think the design looks great, but it could be even cleaner. This is just some constructive criticism. To start, I suggest removing everything except the media controls. You could place the volume slider vertically on the right or left side. Album art isn't necessary, but it could be an option. The "fullscreen" mode still shows the 3-dot menu bar on the top left and looks a bit too busy. Instead, you could use the same hover feature you used for the cinema open/close to display the media controls and everything else on the screen. Essentially, I think it should just be the background art and the lyrics until the user interacts/hovers on the screen with their mouse to display and interact with the media controls.

**Comment by surfbryce** [comment]
I absolutely agree that the media controls should be visible over everything else.

However, a use-case - which many others (and I myself) currently rely on - is the ability to easily glance at who is playing in Cinema mode when its being ran on a second monitor. This is specifically the case when you have smart shuffle, DJ, or any playlist you aren't 100% familiar with playing.

So from that design perspective I don't want to make this important information off by default.

However, I do recognize that it's desirable to hide this information when you may feel like you don't need it.

So to solve that I'm going to add a toggle to the current controls-list for Beautiful Lyrics (where the "Exit Cinema" and Close button can be found). This toggle - just like changing views - will be saved: only requiring you to toggle it once to achieve the effect you are looking for every time you enter Cinema view.

I'll also make some general adjustments;
- With the toggle off (by default) the song information and right-side controls will be mostly transparent - just enough to be readable - but not distracting.
- With the toggle on, these elements will be completely invisible until you hover over the Now Playing bar area.

The media-controls in both instances will be visible, but when the Now Playing bar area is not being hovered it will be slightly transparent and then completely opaque when hovered.

Now I realize I only addressed the visibility concern and not your other layout suggestions. For those I don't see those being implemented anytime soon since the Now Playing bar isn't created by me and is just from Spotify itself. It'll require much more time than I am willing to put in to rearrange things and etc. in CSS - especially for this feature alone - when there are much bigger items I want to get to.

Thanks for the feedback! You should see what I mentioned implemented sometime next week.

**Comment by surfbryce** [comment]
Alright @sealants this should be in the next update when you get it.

Here's a preview:

https://github.com/surfbryce/beautiful-lyrics/assets/80861823/56119fd0-c8b2-4f19-9f8c-92224ed4cf9f

**Comment by sealants** [comment]
Dude, I fucking love it! One last thing I'd recommend is a toggle option to remove the transparent UI on the bottom.
