### ISSUE TITLE
Lyrics Plus?

### ISSUE THREAD

**Issue by Maxdontron** [surfbryce/beautiful-lyrics#59]
I remember supporting Lyrics Plus before, but I don't see any Beautiful Lyrics effect here now, is that a problem?

**Comment by surfbryce** [comment]
There used to be support. I've removed it for now since my extension has its own lyric views/pages.

It was mainly a decision I made when cleaning up the codebase so that all the functionality/CSS can be concise and focused on the actual extension itself instead of external support.

I may add it back in the future but for now there's no plan to add in support for external things at the moment as the focus is to continue improving, stabilizing, and adding features for the extension.

**Comment by Maxdontron** [comment]
> There used to be support. I've removed it for now since my extension has its own lyric views/pages.
> 
> It was mainly a decision I made when cleaning up the codebase so that all the functionality/CSS can be concise and focused on the actual extension itself instead of external support.
> 
> I may add it back in the future but for now there's no plan to add in support for external things at the moment as the focus is to continue improving, stabilizing, and adding features for the extension.

Alright,I see

**Comment by surfbryce** [comment]
@Maxdontron Thanks for the understanding - and I apologize if you relied on this feature - it will be added back in the future, just that there are more important items on my todo list I need to get to before I start adding back external integration!

Thanks for having used the extension!
