### ISSUE TITLE
Glowing effect weirdness when pausing

### ISSUE THREAD

**Issue by Avenred** [surfbryce/beautiful-lyrics#60]
https://github.com/surfbryce/beautiful-lyrics/assets/13921970/3ef4c3c7-8e60-4688-bd11-664b253f43dc

Very minor bug. Lyrics seem to 'jump' when being paused and unpaused. If a lyric is glowing while being paused, the glowing effect is removed but suddenly comes back when unpaused.

**Comment by surfbryce** [comment]
I would love to be able to fix it but unfortunately this is just how Spotify works. Their timestamps are in increments of 0.1 seconds. So when you pause and then hit play its registered as a time-skip just because Spotify has weird play/pause functionality.

Maybe there's a better way to sync it so the timestamp is in real-time but with the way Spotify does it this is a compromise for the time-being.
