### ISSUE TITLE
static background

### ISSUE THREAD

**Issue by nephrittt** [surfbryce/beautiful-lyrics#61]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/78020456/557691de-f5dd-47e3-ae78-5722081b4b5d)
hi, in the description of the plugin there is a gif in which the background is alive, but I have it static and works only in TV mode.

**Comment by surfbryce** [comment]
@nephrittt Restart Spotify, the animation is done in CSS so what this means is that technically no code tells it to move (the browser - in this case Spotify - tells it to). So there really isn't anything I can do to fix that for you since I don't control the actual rotation part of it - I just tell it to rotate.

If that still doesn't work than I'm not sure what else I could do
