### ISSUE TITLE
(Suggestion) Replace all appearances of normal lyrics with Beautiful Lyrics' lyrics

### ISSUE THREAD

**Issue by Drigonis** [surfbryce/beautiful-lyrics#62]
Not entirely sure if this is possible, but it would be nice if it were possible to remove the normal Lyrics button, or just replace the normal Lyrics screen rather than making a new one. I assume it's not that way because the Beautiful Lyrics can be kind of intensive; so some form of low-quality option without bloom and such would be nice.
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/bf8b69fd-954e-439f-912d-c62e316823be)

Also, mostly related - the Spotify full-screen menu (via the button in the bottom-right of the app) could do well with the Beautiful Lyrics on the right side, and the normal Lyrics button removed (if possible).
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/5d1f7130-9bb3-484a-8d72-5918dac09a90)
\* this is the screen I'm referring to

**Comment by surfbryce** [comment]
@Drigonis Enable lyrics in the side-bar to remove the original lyrics page icon.

A new dedicated lyrics page is required since the original one will eventually be removed (most Experimental Features are ones that will become official and replace their older variants). Not only that but it gives me full control over how these pages are navigated and designed. It's not because of performance (since this varies between users based off their setup); but, maximizing performance is always considered first hand in development - Spotify usually is the bottleneck.

Also your suggestion for full-screen adjustments has already been suggested in #48.

I've also made a comment detailing exactly the option to turn off lyric effects and just keep the background here: https://github.com/surfbryce/beautiful-lyrics/issues/49#issuecomment-1643099344

I'm going to mark this as a duplicate since this post doesn't bring in any new suggestions and just echoes existing ones.

**Comment by zero5enpai** [comment]
@surfbryce 
> Enable lyrics in the side-bar to remove the original lyrics page icon.
I'm sorry, where or how does one turn that on? I cant seem to find it anywhere-
