### ISSUE TITLE
There is something wrong with the Extension

### ISSUE THREAD

**Issue by brullax** [surfbryce/beautiful-lyrics#621]
Peru
Spotify para windows (64 bits)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11

Developer Tools Files
[Spotify.html.txt](https://github.com/surfbryce/beautiful-lyrics/files/15436085/Spotify.html.txt)
[Spotify.css.txt](https://github.com/surfbryce/beautiful-lyrics/files/15436086/Spotify.css.txt)

Screenshot of Console

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170674348/2218e17c-6400-4d12-a2da-d7c419323b49)

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170674348/546b0372-b8df-4aec-980a-96f1878eed97)

And this is a screenshot of the problem within spotify

![image](https://github.com/surfbryce/beautiful-lyrics/assets/170674348/476e5b4e-4e65-4724-b292-ffc942484860)

**Comment by pjkitsune** [comment]
Country: United States
Spotify for Windows (64 bit) 1.2.38.720.ga4a70a0e
Spicetify v2.36.11

I'm also having this issue. Just adding to this, this is what it looks like in the lyrics page:
![Screenshot 2024-05-24 112631](https://github.com/surfbryce/beautiful-lyrics/assets/79879329/dc3d9d2c-8d12-4e89-9198-bdb373f1637d)
and this is what it looks like in fullscreen view:
![Screenshot 2024-05-24 112833](https://github.com/surfbryce/beautiful-lyrics/assets/79879329/35dcb6af-f704-4522-8735-139196b1f032)
This only happened since the update

**Comment by krishna-0811** [comment]
same problem

**Comment by brullax** [comment]
ye, I don't know if you can see it soon pls @surfbryce

**Comment by surfbryce** [comment]
@brullax This will be fixed in the next patch, new Spotify update broke existing version
