### ISSUE TITLE
Lyrics wont work for any song

### ISSUE THREAD

**Issue by SirPerryyy** [surfbryce/beautiful-lyrics#628]
Spotify for Windows (64 bit)
1.2.38.720.ga4a70a0e
Spicetify v2.36.11
Since I've updated spotify and spiecify this addon wont work anymore. I can see the addon's button to the full screen lyrics but and when i click it nothing works. Even in the little window in the play view side dont show any liryc.
![Screenshot 2024-05-25 201849](https://github.com/surfbryce/beautiful-lyrics/assets/143434696/a20b0348-d46e-4cf7-b7d3-1b823252ee2b)

**Comment by 4cmc** [comment]
same here

**Comment by ProfessorDomme** [comment]
got the same issue

**Comment by JObersi10** [comment]
Same to me, When i first open Spotify, sometimes it shows once, and never works for any song, even the same song i played for the first song.

MacOS Sonoma Vers. 14.5 (M2 24GB MacBook Air)

**Comment by itsjoexd** [comment]
same here

**Comment by Alesis124** [comment]
seme thing

**Comment by paspermia** [comment]
same to me

**Comment by ApoksiK** [comment]
same to me

**Comment by ApoksiK** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/90096258/67105e66-5440-4650-b830-f035681a5de4)

**Comment by xhos** [comment]
same

**Comment by tr330p** [comment]
same

**Comment by jaygamer252** [comment]
This is probably due to the fact that the creator of the plugin just pulls the lyrics from Spotify itself. Since Spotify restricts lyrics to Premium-only users, the plugin can no longer pull the lyrics to display them. This isn't something the creator could easily circumvent, except by pulling from a third party, which is practically impossible because there isn't a database that would randomly host all the lyrics from Spotify's available songs (if there is, I'd be impressed, lol). The only fix I think might work right now (DON'T TAKE MY WORD FOR IT!) is if you buy Spotify Premium.

**Comment by ivystopia** [comment]
Same, lyrics load forever and never display

![Spotify_uqL2sb4L0p](https://github.com/surfbryce/beautiful-lyrics/assets/5096359/5236876b-5bbe-47c6-82ac-d55f53641a48)

**Comment by surfbryce** [comment]
@SirPerryyy This is because of the most recent Spotify update, will be fixed in the next patch
