### ISSUE TITLE
Add more lyrics sources

### ISSUE THREAD

**Issue by solstice23** [surfbryce/beautiful-lyrics#63]
Currently, AM and Spotify itself are providing lyrics for many songs. However, there are still many songs whose lyrics cannot be provided by them. So I think adding more sources would be a good idea.

The following quote and code snippets are from lyrics-plus.

```
Netease: From Chinese developers and users. Provides karaoke and synced lyrics.
Musixmatch: A company from Italy. Provided synced lyrics.
Genius: Provide unsynced lyrics but with description/insight from artists themselve.
```
https://github.com/spicetify/spicetify-cli/blob/master/CustomApps/lyrics-plus/ProviderNetease.js
https://github.com/spicetify/spicetify-cli/blob/master/CustomApps/lyrics-plus/ProviderMusixmatch.js
https://github.com/spicetify/spicetify-cli/blob/master/CustomApps/lyrics-plus/ProviderGenius.js

Note that Netease provides karaoke lyrics for almost every song because a big proportion of them are AI-synced and may not be so accurate. (Their synced lyrics are accurate.)

**Comment by surfbryce** [comment]
I don't plan on using NetEase as the lyrics often times are inaccurate for a majority of songs that I have viewed - so I have no plan on introducing that as a source.

MusixMatch is the equivalent of AM and Spotify (since they both use it as a provider) combined so there's no reason to include it.

I don't see Genius providing anything new? Do you have any songs that have lyrics from Genius but not from AM or Spotify? Also to note AM uses Genius as a lyrics provider as well.
