### ISSUE TITLE
No Lyrics 

### ISSUE THREAD

**Issue by ddawncom** [surfbryce/beautiful-lyrics#630]
Hello! I've been experiencing an issue with Spotify lyrics recently. It's not just the sidebar; the lyrics feature isn't **working at all**. I tested it with songs in different languages, including English, Korean, Japanese, and Chinese, but the problem persists. When I click the lyrics button, the screen goes blank.

I've seen others report the same problem in the past few days and hours, so it's not just a bug with my Spotify. Here are some pictures I took to illustrate the issue:

![Capture](https://github.com/surfbryce/beautiful-lyrics/assets/160554535/2b41e8da-3032-44ab-bc2c-e29ab3e8ea88)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/160554535/0c6910d0-5070-4861-b265-0adfff594940) 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/160554535/267f879b-01ff-4cd4-87bb-72e3ecd36ca2)

I hope this issue can be resolved soon, as the lyrics feature is a significant part of the listening experience for many users. Thank you for looking into this!

**Comment by jaygamer252** [comment]
This is probably due to the fact that the creator of the plugin just pulls the lyrics from Spotify itself. Since Spotify restricts lyrics to Premium-only users, the plugin can no longer pull the lyrics to display them. This isn't something the creator could easily circumvent, except by pulling from a third party, which is practically impossible because there isn't a database that would randomly host all the lyrics from Spotify's available songs (if there is, I'd be impressed, lol). The only fix I think might work right now (DON'T TAKE MY WORD FOR IT!) is if you buy Spotify Premium.

**Comment by Lucky-56** [comment]
but the [README](https://github.com/surfbryce/beautiful-lyrics/blob/main/README.md) of this Extension quite litterally is:

> ## Karaoke Lyrics for EVERYONE
> If you don't have Premium, Spotify won't give you any lyrics.
> 
> Beautiful Lyrics provides Lyrics to _EVERYONE_ for **FREE**.
> Beautiful Lyrics supports **Karaoke**, _Line_, and Statically synced lyrics with
> additional features like **Background Vocals** and **Side Vocals**.

**Comment by surfbryce** [comment]
@ddawncom Current version of the extension doesn't support certain Spotify versions AND the most recent update broke it. Both of these pain-points will be fixed in the next patch
