### ISSUE TITLE
HI I HAVE THE MOST ORIGINAL IDEA

### ISSUE THREAD

**Issue by Jpeguero03** [surfbryce/beautiful-lyrics#636]
hi can u make a DeskTop widget for te lyrics??? that opens automatically with the spotify? it may look like the lyrics in IG stories very minimalist xd ty for reading but could look good

**Comment by H0UXD** [comment]
@surfbryce I'm sure he means something like the lyric cards, but instead of in the spotify app, it's on your desktop. This is an example I edited. (It's not a good picture but should get the idea throught) 
![image(1)](https://github.com/surfbryce/beautiful-lyrics/assets/70112674/076e1e76-729b-417f-a5b2-09baf68cd211)

**Comment by oldschoolvirgo** [comment]
lyricify already does this 

https://github.com/WXRIW/Lyricify-App

**Comment by surfbryce** [comment]
@Jpeguero03 Forgot there was an existing issue of this already, #172.
