### ISSUE TITLE
Incorrect Lyrics

### ISSUE THREAD

**Issue by Drigonis** [surfbryce/beautiful-lyrics#65]
see below:

Dua Lipa - We're Good
* Beautiful Lyrics
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/0f8dbed6-2d7f-4a45-8e30-d82dce3fb0e5)
* Correct lyrics
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/f5320269-6bfc-4479-9ca4-6a645c0ccb3a)

Lizzo - Juice
* Beautiful Lyrics
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/dbf4878c-ff43-466e-a5e8-f92061440081)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/8263ad53-56ae-4a80-9a2e-3d063b93dcf2)
* Correct lyrics
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/8c049118-8933-4722-8f02-6addcc5b6572)
![image](https://github.com/surfbryce/beautiful-lyrics/assets/83103389/cf3eb6a2-0e85-47ef-bebf-ad8ad1f91ed4)

some others have slight differences, but these are the main instances I've seen where the lyrics are just straight-up incorrect. is it drawing from an outdated version of Musixmatch? not entirely sure how it works, so idk what's causing this

**Comment by surfbryce** [comment]
@Drigonis I think Spotify actually has the incorrect lyrics for Juice (https://genius.com/Lizzo-juice-lyrics) - listening myself it even sounds like "I, like" and not "I'm" unless the "m" syllable is really really buried deep in the mix.

For the Dua Lipa song though there is a huge issue there as when I checked with the lyrics provider I'm using it has the correct lyrics.

How my thing works is that I get the ISRC from Spotify and search for every song that matches that and then get the lyrics from all of those. Clearly one of them is probably a PG-rated version of the song and it picked up on that instead.

I'll look into this soon and see what I can do to fix it.

**Comment by surfbryce** [comment]
alright so @Drigonis it's definitely been a long time since I last looked into this.

I worked on a solution that basically gets rid of options that are identical to each other and keeps count of how many identical lyrics there were.

The incorrect version has 98 identical versions. Where the correct one is by itself.

So analytically it's quite literally impossible for me to find the original in this instance.

The bigger issue is that technically all these versions are owned/created by Dua Lipa. So I think the bigger issue is that somebody down the line decided to censor out that part of the lyric for some reason and everybody started using that variant. The original of course uses the correct lyrics but it's the only version in existence to do so.

You could say that I could use the one that is the least similar to the group - and that is true I could in this instance - but of course I don't know how that would affect a bunch of other songs. It wouldn't affect whether or not one is synced or not but more importantly it would possibly affect the actual word choice being correct.

It's possible that a censored version could be the only one and all the others are correct. In this instance it would drastically backfire and create the same issue in another circumstance.

So I'll have to think about what to do here.

**Comment by surfbryce** [comment]
Actually @Drigonis I found a super simple solution.

I think a long time ago I tried to sort the lyrics by their release-ids; so basically, releases put out first were prioritized. Not sure why I didn't keep doing this but I remember it messing up the results.

Anyways, this is the solution I came up with. I do this release-id comparison in the sorting process ONLY IF the score is the same as the comparison score AND those scores are above the minimum syllable score. If they are not above that meaning they are at the maximum Line-synced then I do the identical comparison to determine which variant has more versions of it.

This should work for everything since when it comes to syllable synced lyrics even the older versions are put to the correct versions, and usually what the newer versions rely on.

**Comment by surfbryce** [comment]
@Drigonis Coming back to this, "We're Good" is an extremely difficult situation to handle simply because Spotify/Apple Music do NOT have the same release dates for these clean/dirty versions of the songs. However, I did manage to get it so that they are separated, but the single version still uses the clean version. Unfortunately, I don't think there's anything I can do about that. Sorry!

But in the following update this issue should be fixed relatively.
