### ISSUE TITLE
Appreciation and Contribution (Not an issue)

### ISSUE THREAD

**Issue by beemilkz** [surfbryce/beautiful-lyrics#66]
Hello there,

I wasn't sure where else to contact you, so I'm reaching out this way. First and foremost, I want to express my admiration for your awesome extension! I am really impressed with how good the lyrics look. It really adds to the listening experience. I also want to contribute to the lyrics.

I've noticed that some songs lack complete lyrics (synced) and instead, they seem to be filling in slowly. I'm curious to know whether these lyrics are added manually or if they are generated automatically.

For example, in Radiohead's song "Just," the lyrics are displayed like this:

![image](https://github.com/surfbryce/beautiful-lyrics/assets/93970766/76a0631d-ab66-4fe9-9509-8fccc9cdbf0b)

Could you tell me if these lyrics were added by a contributor or generated automatically?

Thank you for your time, and I'm looking forward to contributing!

**Comment by surfbryce** [comment]
@beemilkz There is no contribution feature - in the future there will be a built-in editor to adjust lyrics (text/timing) and to create them. When this does release there will be a panel for looking at these submitted contributions and initially only I will have access but eventually as I find more people who are suited for the job and are reliable they will also get access to that panel.

Also no lyrics are ever AI-generated - there is no technology that exists (yet) which can do it reliably or at mass in high quality.

However, the lyrics-provider I use (in addition to Spotify) seems to weirdly have these words spaced out like this. Unfortunately there is not much I can do on this front to change that. Since it's syllable-synced this means that the record-label (or the Radiohead team) purposefully wrote the lyrics this way.

For now this is the way it'll have to be - I apologize for the inconvenience in your experience. This definitely is harder to read :[

I also appreciate your praise - it means a lot - glad you are enjoying the extension!
