### ISSUE TITLE
Permission to use this extension in SpotifyNoPremium

### ISSUE THREAD

**Issue by Daksh777** [surfbryce/beautiful-lyrics#684]
Hey @surfbryce 
Thank you so much for creating this extension, you are doing amazing work :)

I was unable to find any other way to contact so I'm creating this issue. 
I maintain the [SpotifyNoPremium](https://github.com/Daksh777/SpotifyNoPremium/) repository, which was basically started to bring non-developers to using Spicetify and make the process easy using scripts.

Some users were asking if it would be possible to bring lyrics to Spotify: https://github.com/Daksh777/SpotifyNoPremium/issues/126
I was wondering if it would be okay for me to use the extension in my repository (with all the credits and link to this repo)?

**Comment by Diibee** [comment]
Hi you can contact him on discord he's @socalifornian

**Comment by surfbryce** [comment]
@Daksh777 I'll have to say no on this, I have a few reasons as to why.

First, it is taking people away from my repository. Currently, users can find this repository either through Marketplace or GitHub directly (if they are manually installing). If you included this as part of your "package"/"theme", they would go to your repository if they had any issues/suggestions with/for my extension. The Spicetify GitHub/Discord already has issues with people going there for those reasons because they think Spicetify made Beautiful Lyrics. It's worse for both you and me, even if you included an issue template stating something about the lyrics, it's now an even worse UX experience.

Another thing is that my entry-point file WILL change from time to time, when I make that push to production I can guarantee that users will be on it (if installed through Marketplace) within a couple of hours. I cannot have the same guarantee if it was a part of your "package".

Another issue I have is really just the concept of your "package". You say it's for "non-developers", but Spicetify is already incredibly simple to install (although, the UX can be improved and clarification that "Marketplace" is just an extension should be added), and with Marketplace it's even simpler to get what you want on Spotify.

When I look at that repository all I see is "we took ablockify by riri and then added some CSS to remove the other elements that it doesn't cover", it's on the edge of being able to be called "transformative" and takes away attention from the actual repository. You mention credits/link, and all I see in your current README is a tiny "(Source)" addition to the listed feature that uses that extension.

I'm not a fan of what you are doing here and I don't think it needs to exist; I appreciate you asking though.

**Comment by rxri** [comment]
tbh, there's no need for the `SpotifyNoPremium` theme anymore since for example [`adblockify`](https://github.com/rxri/spicetify-extensions/tree/main/adblock) does everything the theme did (except the pointer cursor but that's really really picky and unnecessary). After re-thinking it, I stand with @surfbryce on this plus you could just archive it at this point

**Comment by Daksh777** [comment]
Thank you for responding @rxri @surfbryce 

I agree with all your points @surfbryce, I'm not really doing a lot at this point as it used to be before, especially since I've been focusing more on my career now. 

It's just a little more convenient for people to use a batch file which does everything because some don't know much about PowerShell and don't know how to run those commands by going through the documentation, I've had some contact me in the past, and that's why I've kept it as is. 
I do indeed agree that SpotifyNoPremium at this point is not needed. I've had this conversation with @rxri before as well mentioning how I want to archive the project but there's a decent amount of people who use it and new people who come via internet, and that's why I couldn't archive it.

For the credits, I'm absolutely happy to give a full mention of the username and GitHub repository link if @rxri wants instead of source text thing.
I don't want to steal credits or your work, there's no gain for me in stealing anyone's work, I'm sorry if there's something that makes it seem that way and I'm happy to make changes if anyone wants.
