### ISSUE TITLE
pls add spotify font

### ISSUE THREAD

**Issue by Stepqq** [surfbryce/beautiful-lyrics#72]
pls add spotify font in lyrics :(

**Comment by surfbryce** [comment]
@Stepqq The Spotify font itself is very aggressive and too spaced out compared to the current font - I'm curious though - what does the font look like for you?

The main thing is that I'll consider adding it as a fallback font so when the font I picked out specifically isn't available to you then it'll fallback to the Spotify font - but I'm curious first to see how it looks for you to see if its necessary.

**Comment by surfbryce** [comment]
So just going to say flat out that there is no plan to switch to the Spotify font and that the Apple Music Font will be the choice of font as it's the best looking one I can find for this.

It's friendly and compact so that its pleasant on the eyes while also being defined and spaced out enough to be easily readable.

Windows right now doesn't use this font but it will soon - so if you are using Windows you should see this font being used.
