### ISSUE TITLE
Not working at all

### ISSUE THREAD

**Issue by GhostyBoi21** [surfbryce/beautiful-lyrics#735]
### How did you install Beautiful Lyrics?

Marketplace

### What is the Bug/Issue?

I installed and re-installed it many times yet i still get the default spotify lyrics, worked before but now it doesnt anymore. Any fix? Setting i'm missing?

### What Country are you from?

UK

### What Operating System are you using?

Windows

### Spotify/Spicetify Information

Shortcut no work :(

### Spotify HTML/CSS and Console Screenshots

![image](https://github.com/surfbryce/beautiful-lyrics/assets/173091755/a0bd20aa-6807-4fe2-ac5f-243889b56127)

### Information Checklist

- [X] Spotify/Spicetify Information
- [X] Spotify HTML File
- [X] Spotify CSS File
- [X] Screenshots of Developer Tools Console Tab

**Comment by surfbryce** [comment]
@GhostyBoi21 You are using the wrong version of Beautiful Lyrics. Fully uninstall from Marketplace, then reload Spotify, if it is still installed then uninstall it again and reload Spotify.

I know this is the case because of that "async" error message, which isn't possible in the latest version of Beautiful Lyrics

**Comment by LazerSkar** [comment]
had this problem before and i have reinstalled since and my lyrics work. great mod you have btw, ima list afew songs id love to have live...
i hope its not alot of effort for these songs to get a live version :)
