### ISSUE TITLE
Full Screen Button Duplicated/Doesn't Appear

### ISSUE THREAD

**Issue by Hsarfs** [surfbryce/beautiful-lyrics#74]
A few days ago, a button appeared in the bottom right corner of Spotify, allowing me to activate a fantastic full-screen function. However, it seems to have disappeared now. Is this a feature of the Spotify, or was it part of the extension?, how can I reactivate it if it goes missing?

**Comment by surfbryce** [comment]
@Hsarfs Beautiful Lyrics will override the functionality of the fullscreen button. There shouldn't be an extra button, so if you have the fullscreen button present you can just click on that to do it. If the fullscreen button for some reason isn't there anymore - please let me know and send a screenshot. Also try restarting Spotify first to see if it brings it back. Otherwise we can work together to figure out how to fix this!

**Comment by Hsarfs** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/98976339/e0dc916e-fb25-492b-9b14-2b75c0344b82)
Previously, the button was located where I marked the blue dot, and it resembled two arrows pointing in opposite directions.

**Comment by surfbryce** [comment]
I'm aware of what it looks like - Spotify has its own fullscreen mode. I simply just override the click functionality so instead of opening Spotifys it opens my own. It's a little odd that it is missing though.

If you don't mind - could you run this command: "spicetify apply enable-devtools".

And then right click on an open area that doesn't show the spotify context menu and open up developers tools. Once you're there go to the console tab and screenshot

**Comment by Hsarfs** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/98976339/241f4edf-96c0-426a-8227-4663ca39ff83)
Here it is!

**Comment by surfbryce** [comment]
@Hsarfs Make sure you are on the console tab - it looks like you are on the Elements tab right now. Just click on the tab to the right of it.

**Comment by Hsarfs** [comment]
![image](https://github.com/surfbryce/beautiful-lyrics/assets/98976339/5954af9e-628c-428b-b6af-3bb9bf82b917)
I am sorry for my error

**Comment by surfbryce** [comment]
No problem @Hsarfs, this screenshot is after you've opened Spotify and it's missing the fullscreen button right?

Also, since you're on windows - can you click on the three dots in the top left of Spotify and go to "About Spotify" and screenshot everything there? Thanks!

**Comment by Hsarfs** [comment]
Yes, the button is still missing
![image](https://github.com/surfbryce/beautiful-lyrics/assets/98976339/6574c8a1-d235-4829-a6de-c7598f1a8871)

**Comment by surfbryce** [comment]
@Hsarfs Hmmn, alright seems to be normal on that front. I'll have to see why it decides to delete itself for some reason. Can you let me know what theme you are using? I think it might be because of that - I've had this happen to me a long while ago and it was on a theme - so it might be because of that.

**Comment by Hsarfs** [comment]
I attempted to reboot the PC, but the button disappeared again. To make it reappear, I had to reinstall the extension.

**Comment by surfbryce** [comment]
@Hsarfs I'm going to mark this as a bug and see if there's a better way for me to handle the fullscreen override functionality so it gets rid of the chance of having duplicate fullscreen buttons and the issue you were having

**Comment by surfbryce** [comment]
@Hsarfs Alright this should be fixed now - let me know if this still happens to you and I will reopen the issue
