### ISSUE TITLE
eevee spotify + beautiful lyrics

### ISSUE THREAD

**Issue by Cosmic1212** [surfbryce/beautiful-lyrics#740]
### What are you Suggesting?

a Feature

### What is the context behind this Suggestion?

https://github.com/whoeevee/EeveeSpotify

It's not a problem with beautiful lyrics just thought it would be a cool feature since Apple Music has it already

### What is your Suggestion?

adding support for mobile spotify in collaboration with eeveespotify to bring these lyrics to mobile

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Cosmic1212 It's not possible. What they do is basically redirect endpoints/requests that the Spotify app makes. They don't modify the app itself nor adjust its visuals.

It is currently impossible to change visuals on the app versions because they are entirely native to their platforms (iOS/Android), we can only do it on Desktop because the Spotify app runs on a browser engine which means we can tap it into it just like a website.
