### ISSUE TITLE
Song API Documentation

### ISSUE THREAD

**Issue by sealldeveloper** [surfbryce/beautiful-lyrics#746]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

The API you have for this extension is really nice, and I would love to be able to utilize it for a personal project.

### What is your Suggestion?

To provide access to the API and potentially some rudimentary documentation. Or perhaps some information about how the backend API operates so we could replicate something of our own.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@sealldeveloper Right now this isn't planned at all, the lyrics backend is not what I would consider "developer ready" and is only really ok being used by the extension because the only expectations for how it should work and its stability are from me.

Sometime this Summer I'm hoping to get to a Lyrics Editor update in the extension as well which is going to massively change the API for my Lyrics Service.

It won't be until **AFTER** that update that I'll be open-sourcing the backend and marking it as "developer ready".

The other thing is that it is directly connected to Spotify on the backend, so the things you pass to it are Spotify related not specifically ISRC related or anything else. So that adds a barrier of entry to using it externally outside of the Spotify ecosystem.

**Comment by sealldeveloper** [comment]
> @sealldeveloper Right now this isn't planned at all, the lyrics backend is not what I would consider "developer ready" and is only really ok being used by the extension because the only expectations for how it should work and its stability are from me.
> 
> Sometime this Summer I'm hoping to get to a Lyrics Editor update in the extension as well which is going to massively change the API for my Lyrics Service.
> 
> It won't be until **AFTER** that update that I'll be open-sourcing the backend and marking it as "developer ready".
> 
> The other thing is that it is directly connected to Spotify on the backend, so the things you pass to it are Spotify related not specifically ISRC related or anything else. So that adds a barrier of entry to using it externally outside of the Spotify ecosystem.

Sounds good, I'm happy to wait till later to have a look. Thank you for your time.
