### ISSUE TITLE
Improved Full-Screen/ Cinema Layout

### ISSUE THREAD

**Issue by Gmemster** [surfbryce/beautiful-lyrics#748]
### What are you Suggesting?

an Improvement

### What is the context behind this Suggestion?

The current Full-Screen experience is so bad. It is too bulky and need some simplification. With the lag sometime when using this extension the full screen view is terrible and easy to misclick on buttons

### What is your Suggestion?

Something like the default spotify full screen while adding lyrics! As simplify as possible so it looks modern and clean.

### Suggestion Checklist

- [X] You clearly titled/explained your Suggestion.
- [X] You accurately described/contextualized the reasoning behind your Suggestion.
- [X] IF applicable to your Suggestion, you provided visual examples/references to accurately represent what you are Suggesting.

**Comment by surfbryce** [comment]
@Gmemster What are you talking about..... this is among the cleanest layouts for Fullscreen that I've seen ever.

Idle:
<img width="1715" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/e2afddc1-e3d3-4b11-8c29-4f456cc0ca5c">

Mouse hover over Cover:
<img width="1718" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/4cd1eeeb-2dd7-42c6-9730-86428c300a4b">

Are you sure that you're using the right fullscreen, I'm going to close this, but feel free to respond with a screenshot of what fullscreen look like for you. It's already incredibly clean and a significantly better layout than what Spotify provides.

**Comment by Gmemster** [comment]
@surfbryce Don't you think when Mouse hover over cover the cover is fill with thing and feels pretty complicated?

**Comment by surfbryce** [comment]
@Gmemster Sorry, I actually misspoke. It slightly fades in whenever the mouse moves on that side of the screen and then fades in fully when over the cover. The slight fade in when the mouse moves outside the cover is to indicate to the user that the controls are located there, with the full fade in on hovering the cover being for intractability (obviously).

You say it feels pretty complicated, I'm struggling to find out how. You still have to move your mouse over to the controls regardless of whether or not they are always visible or hidden away like I've done here. And even if you don't move your mouse from the controls, in both layout variants the controls will always be visible and immediately accessible.

So there isn't a technical difference in terms of what you have to do to access them, the only difference is where they are positioned and whether or not they are always visible, which are not complexity factors and are just visual preferences.

If you can explain to me why you believe it is complicated, we can have a discussion about possible changes.

From the way I see it, having this information visible for 100% of the time when it is only used for 5% of that time makes no sense. I've designed this interface so that it isn't complicated but still leaves the user interface simple and easy to look at.
