### ISSUE TITLE
Apple Music font on Windows

### ISSUE THREAD

**Issue by daragamer12** [surfbryce/beautiful-lyrics#75]
hello dev!
great job, been having fun with the plugin
my question is, idk if its just me, but can the lyric font for windows be changed to apple music's default font instead of spotify's?

**Comment by surfbryce** [comment]
It's actually not Spotifys default font since that isn't one of the fallback fonts I assigned - but what does it look like on Windows - I would love to see a screenshot!

I'll see what I can do to get the Apple Music font available on windows - its a default font on Apple so MacOS users (myself included) get first-class treatment because of that when it comes to the fonts.

**Comment by daragamer12** [comment]
hello! thanks for replying back on time! was jamming to some music lol
here's the sc you requested: 
i tried to change it manually in css, but to no avail.
![Screenshot 2023-07-27 052347](https://github.com/surfbryce/beautiful-lyrics/assets/96257337/fd667d75-40cb-42f3-8df2-fae538d87ad1)

**Comment by surfbryce** [comment]
@daragamer12 Yeah definitely doesn't look as good, I'll see what I can do to bring that font over to Windows!

**Comment by surfbryce** [comment]
@daragamer12 In the latest update this should be a thing now - where the font is the same on every platform.

**Comment by daragamer12** [comment]
just saw this! thanks so much, just booted it up! :D 
![image](https://github.com/surfbryce/beautiful-lyrics/assets/96257337/af873635-0aa9-4f07-bdb6-7ac1037b486a)
