### ISSUE TITLE
Add support for Lyrics Plus?

### ISSUE THREAD

**Issue by HuyHung1408** [surfbryce/beautiful-lyrics#8]
Also, if you add animated background into Lyrics Plus, I suggested keeping our own config (font, alignment, ...) in Lyrics Plus.

**Comment by surfbryce** [comment]
That shouldn't be an issue - I'll look into adding it

**Comment by surfbryce** [comment]
Alright Live-Backgrounds have been added to Lyrics Plus in surfbryce/beautiful-lyrics@d0ab105

I won't be able to support the blurring/text-size increase effects because of the way Lyrics-Plus incorrectly does its sung-text highlighting. When a lyric has already been sung they mark it as "active" rather than "highlight" - which messes with how I store the lyrics.

Without making my current operation less efficient I unfortunately cannot support those features. Backgrounds should be fine though!

You'll see this in the next release when it comes out - most likely tomorrow!

**Comment by HuyHung1408** [comment]
> I won't be able to support the blurring/text-size increase effects because of the way Lyrics-Plus incorrectly does its sung-text highlighting. When a lyric has already been sung they mark it as "active" rather than "highlight" - which messes with how I store the lyrics.

Thanks,  it's not a big deal for me since I don't use those features.

**Comment by HuyHung1408** [comment]
<img width="732" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/86362423/ac23a3d5-08c8-45c8-b3af-205ac1ae2aa3">
Absolute beautiful!
