### ISSUE TITLE
Supported songs for the in sync animation?

### ISSUE THREAD

**Issue by AscendedSion** [surfbryce/beautiful-lyrics#81]
What are the current supported songs for the in sync animation? ive noticed that most underground songs don't have this animation.

**Comment by surfbryce** [comment]
@AscendedSion Whatever has Syllable-synced lyrics in Apple Music will have syllable-synced lyrics in the extension. Whatever has Line-synced lyrics in Apple Music OR Spotify will have them in the extension.

If neither of those platforms have them and only have the text themselves it will show the text.

Otherwise it will display that there are no lyrics available.

In the future there will be a way to submit your own lyrics via a lyrics editor in the extension so you can have your own syllable/line synced lyrics and if reviewed by somebody and approved will become the official lyrics for everybody else as well.

I don't personally go out of my way to write the lyrics or to sync the lyrics for the song. I use multiple other services to get these lyrics. The way they get their lyrics is from the artists/label companies themselves. So what it seems is that your "underground" artists either a) haven't bothered syncing/adding lyrics to their own songs or b) their label or team haven't bothered doing so as well.

If you do find that there are synced lyrics on either of those Music Platforms then I would be more than happy to have you create a new issue about it. You would of course need to screenshot the song on either of these platforms and then screenshot what my extension is showing so I know specifically what's happening. Otherwise there is nothing I can do since this isn't a problem with the extension.

I appreciate the heads up though. Also I just want to mention it would be better in the future (for anything you make an issue with) that you actually list what is having problems - in this case - you would have listed a couple of songs that don't have synced lyrics. Again though; only do this IF there are synced lyrics somewhere else and there aren't in the extension.

**Comment by AscendedSion** [comment]
Thanks for the response, I had no idea that the artists had to sync their lyrics.

The lyric editor feature sounds good.

:)
