### ISSUE TITLE
Newest Spotify Update causes Side-Card to not appear

### ISSUE THREAD

**Issue by retrobase** [surfbryce/beautiful-lyrics#84]
Just what title says, after updating Spicetify and marketplace, Beautiful Lyrics no longer works. I've tried every possible thing to fix this but nothing has worked.

**Comment by surfbryce** [comment]
@retrobase It seems to be working fine for me - I also don't have a Spicetify update available at all - only marketplace.

Would you mind sending the version of Spotify/Spicetify you are on?

If you are Windows click the three dots in the top left and go to "About Spotify" and screenshot that. Or on MacOS click Spotify in the top left and do the same.

I'm also interested; are the rest of your extensions (not themes since they are retrieved in two different ways) also working?

It would also be awesome if you could run the command "spicetify apply enable-devtools", then right click on an empty space in Spotify (where it doesn't show the Spotify right click menu), and open up "Developer Tools", and finally click on the Console tab and screenshot everything that is there.

All of these together should be enough to help resolve your issue. But I'm pretty certain it's not an issue with the extension.

**Comment by DuumXH** [comment]
Can confirm that its semi-broken on latest version of Spotify. There's no lyrics on the side panel, doesn't get themed. Full Screen and lyrics page does work.
Spotify for Windows (64 bit)
1.2.17.832.g15fa351e
Spicetify v2.22.1
![image](https://github.com/surfbryce/beautiful-lyrics/assets/36641860/c604dcb7-a7ac-49c0-9b73-07aa5df075ad)

**Comment by surfbryce** [comment]
@retrobase if you are on the same version as @DuumXH then it's most likely that Spotify changed a few things that I use to recognize stuff.

I myself do not have access to the latest version of Spotify yet:
<img width="264" alt="image" src="https://github.com/surfbryce/beautiful-lyrics/assets/80861823/bc0ce9e0-06c1-41c5-95b1-cd95a72b375e">

So I will have to wait until tomorrow (should have access to it by then) or until I get the update to determine what I can do to fix it. For now, there is nothing I can do atm: given that there are no errors reported in your screenshot @DuumXH

**Comment by surfbryce** [comment]
@DuumXH Yep you are absolutely right, the new update does break the side-card background and lyrics. I'll look into what specifically is the issue and get an update out today. Thanks for reporting here!

**Comment by surfbryce** [comment]
Alright @DuumXH and @retrobase this update should completely fix and add support for the newest Spotify (3.1.8)
