### ISSUE TITLE
High CPU Usage (MacOS)

### ISSUE THREAD

**Issue by zerol1ght** [surfbryce/beautiful-lyrics#85]
When I have the lyrics side card opened the CPU usage goes really high, but when I close it they stay relatively low.
It's a bit annoying because it makes the cpu temp go up and the fans kick in. (The fans rarely need to even spin, they always stay at 0 rpm)
I don't remember having this issue a couple of days ago.
I don't think that the dynamic background needs that much power to run.
Any thoughts?

### Lyrics Card Closed:
<img width="968" alt="2023-08-03_9 10 27 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/77642830/c463dcaf-099c-4945-8341-90b3c5cf4dab">

### Lyrics Card Opened:
<img width="979" alt="2023-08-03_9 07 21 PM" src="https://github.com/surfbryce/beautiful-lyrics/assets/77642830/f2620805-a74d-4d7f-b913-378ee77700c4">

Spicetify Version: 2.22.1
MacOS Version: 13.4.1
Apple M1 Pro, 16gb ram

**Comment by surfbryce** [comment]
@zerol1ght A lot of people typically think that the extension shouldn't need much to run - and this makes sense, as you as an end-user only see what is visible to you - but the reality is that Spotify is basically a cut-down browser. This means that all the disadvantages and performance issues that come from browser based rendering are what I inherit with this extension.

Windows and MacOS both have these issues where the GPU, CPU, and Memory are used more than what you would expect. This is just a thing that comes from the inefficiencies. Memory gains maybe 400mb and this is because when you render things you have to store all this information somewhere to calculate all the stuff to go on screen (browser based applications like Discord, Spotify, Steam, etc. all suffer from this). GPU wise - well - we have to render stuff and render a lot (we're rendering three large images that are blurred, that takes some power in the browser). CPU-Wise the browser has to calculate all the visual properties and stuff to pass to the GPU (plus all the other systems that are running, like my extension for example).

I like to think that my code is as optimized as possible on the lyrics-front and any other good alternative I've made to my current approach to the background takes just as much usage.

This is just kind of the downside of a browser rendering all of this - it's a generalized approach - which means you lose a lot of performance because you have to make one thing work for every possible combination.

I also run on a 16gb M1 Pro just to let you know. Although I'm surprised your fans are kicking up that much. Mine never really do regardless of what I have running. Although, if you are in a warmer room or area then they would kick up a lot faster.

So I'm not sure why your performance tanked compared to a few days ago. I can't really answer to that.

Anyways for now - the moral of the story is - I can't do anything about the performance atm; and unless somebody comes along with a pull-request that solves things that I overlooked, we're going to have to suffer with the way rendering is done within Spotify.

**Comment by zerol1ght** [comment]
Thanks for the detailed explanation, I already knew the majority of things you said but I appreciate the effort you put into the answer.
I can't really hear the fans so I can pass over it. (I have 25°C in my room)
It was just strange to feel the macbook warm so I took a look at the temps.
I don't remember this happing before but maybe I never noticed it 🤷🏻‍♂️.

Another minor thing, I have the crossfade song effect turned on, and when a song changes, the lyrics get out of sync and I have to pause and play the song to re-sync them (Very noticeable with the word-by-word synced songs). I'd appreciate if you could take a look at it.

Thanks again for your time.

**Comment by surfbryce** [comment]
@zerol1ght If you can create a new issue for that then I can take a look at it when I can. Spotify does a very poor job of synchronizing itself with its own internal timestamp so it might just be a Spotify API issue but I'll see what I can do.
