### ISSUE TITLE
Lyrics out-of-sync with "crossfade song" effect.

### ISSUE THREAD

**Issue by zerol1ght** [surfbryce/beautiful-lyrics#86]
The lyrics get out-of-sync on song change with the crossfade effect turned on.
To re-sync them, I need to pause and play the song. It is very noticeable with word-to-word synced songs.

**Comment by surfbryce** [comment]
@zerol1ght After looking into this I don't think there is anything that I can do to fix this. 

I rely on Spotify to tell me what the playback progress is and then I fill in everything in-between so we can get these smooth animations. It looks like not even Spotify is able to accurately report what that progress is since when I pause and play (with any crossfade) Spotify itself has changing values.

I'm assuming what Spotify does is that it only gets the playback progress from its backend (the part we can't access) when we play/pause. Then it does what I do which is just increment that timestamp every now and then. Although, I do it every render-frame and Spotify does it every 0.1 seconds.

I apologize I can understand it's annoying from my side there is nothing I can do

**Comment by surfbryce** [comment]
Actually I stand corrected, I found a way to get this to be extremely accurate and on-time even with fades. So this should be good to go in the next update. It actually cleaned up a lot of my code too!

**Comment by surfbryce** [comment]
Alright @zerol1ght this should be fixed in 3.1.8. Please let me know if you still run into issues and I'll reopen it.

**Comment by zerol1ght** [comment]
I updated everything and I still have this issue, the lyrics start around 2 seconds before the song. (I've tried with multiple songs) 🥲
Don't worry too much if you can't figure out how to fix it.

**Comment by surfbryce** [comment]
@zerol1ght I'll see what I can do but its a very complicated problem all because Spotify doesn't do that good of a job with updating the actual timestamp being used.

**Comment by surfbryce** [comment]
Alright @zerol1ght in this upcoming update you should see a major improvement in the syncing. It's a little hacky since I have to trigger a play/pause to get the timestamp to sync up properly again but it should work to get it synced up 100%.

Let me know how it works out for you when the update comes out

**Comment by surfbryce** [comment]
Nvm @zerol1ght, the implementation I put in seemed to disrupt the way sound played at the beginning for other people so I had to revert this change. I'll have to find a similar technique that forces Spotify to update the timestamp. Sorry for the false-hopes!

**Comment by surfbryce** [comment]
Alright @zerol1ght I found a solution that shouldn't affect anybody at all.

I realized I don't even need to pause, I just need to call a play method and it'll force the timestamp to sync up.

I had to do some gutting to prevent errors from being spammed in the console (not actual errors, just ones complaining about how the song is already playing - but we know and don't care). You should see this in the 3.1.10 update.

**Comment by zerol1ght** [comment]
Thanks, I'll try it out.
btw if it can help even a volume change should update the time stamps.

**Comment by surfbryce** [comment]
@zerol1ght Wasn't aware of that. If this works without causing a disruption then this should be the best solution since it doesn't change any state at all. It just forces an update.

So hopefully it doesn't cause any problems (it shouldn't realistically)

**Comment by zerol1ght** [comment]
Now the lyrics are always synced, thank you.
