### ISSUE TITLE
Consistent line count and scroller

### ISSUE THREAD

**Issue by D3SOX** [surfbryce/beautiful-lyrics#9]
When a lyrics line becomes active, the font size will be enlarged. This has the side effect of some lyrics lines that are shown in one line when inactive becoming two lines when being active. I think this makes it less readable.

https://github.com/surfbryce/beautiful-lyrics/assets/24937357/4616e3e9-bcc2-4bee-ab00-b52a2651fa01

What I also noticed is that because of the change in height, it sometimes has to correct the scrolling position after the fact, which makes it look not really smooth, kinda clunky in my opinion. This can be seen in the clip above and also here with no line count change:

https://github.com/surfbryce/beautiful-lyrics/assets/24937357/21a608e2-a78a-4668-a3a2-e2e08b3e8bf0

As I solution for the first problem, I'd suggest an option to disable enlarging the current line font size
For when it's still enabled, it would be nice if the scroller could take the change in font size into account and therefore instantly scroll to the correct position without adjusting after the fact

**Comment by surfbryce** [comment]
This will be fixed in the next major release; specifically, issues #15 and #14 will solve this.

**Comment by Slllava** [comment]
Every time a line is switched, there is a sharp animation of shifting by a few pixels. Also, for the fact that the font size is used, word wrapping is triggered.
https://share.cleanshot.com/pNjfvrSc

I tried using scale to zoom in. And it removes the word wrap problem. But there is another problem related to autoscrolling.
https://share.cleanshot.com/CgMSStnC

**Comment by surfbryce** [comment]
@Slllava Please refer to the comment I made above.

As a quick reference for anyone else who stumbles upon this; this issue is due to how Spotify implements their scrolling mechanism - I cannot do anything about this directly without making modifications to their DOM structure. The only thing I currently change is the size of the font itself. Spotifys implementation for auto-scrolling and line syncing seems to be hardcoded. This means that they programmed it around the situation that everything is the way they set it up to be - which in this case - the font-size is not what they expected it to be.

To sum up #15 and #14:
- #15 I plan to have full syllable and line synced lyrics available (with background vocals support) from an endpoint which takes an ISRC and returns back the best set of lyrics it can find. This is already finished and implemented into the Extension and has been a part of the extension for a few weeks now in preparation of this big release (so that lyrics load extremely quickly on launch)
- #14 This is the visual side to the backend I just mentioned. This will introduce new live lyric visuals and a custom lyrics-scroller (these will look like those found in Apple Music).

The issues with how lyrics are presented now will no longer be a thing once this major update comes out since Spotifys implementation will no longer be there. This will come with the benefits of lyrics just being a better experience overall.

**Comment by surfbryce** [comment]
Forgot to close this - but this is no longer an issue!
