### ISSUE TITLE
Lacking Local File Support

### ISSUE THREAD

**Issue by Iwan342** [surfbryce/beautiful-lyrics#92]
The button to turn on beautiful lyrics is still on, but it shows no lyrics and shows the dynamic art of the previous song listened to, there is also no text saying "This song doesn't have any Lyrics!" (the text only shows up if the previous song doesn't have lyrics). 

normal song with lyrics:
![image](https://github.com/surfbryce/beautiful-lyrics/assets/64904110/4583d9ae-9593-4bd1-9eea-93b89b307351)

local file song with no lyrics and the same dynamic art as the normal song
![image](https://github.com/surfbryce/beautiful-lyrics/assets/64904110/2617820d-d18f-4223-ac33-e11afad14220)

imo a good way to fix this is just to remove beautiful lyrics for local files songs.

**Comment by surfbryce** [comment]
@Iwan342 Yeah that's not a very good solution to just flat out remove them.

Eventually there will be a lyrics editor and you'll be able to use it on local files. I want this support so that custom album mixes I have made myself can have the same experience as an officially published song on Spotify.

I've been meaning to do this but haven't found the time, I'll look into it today and see what I can do to support local files straight away.

**Comment by surfbryce** [comment]
Alright @Iwan342 this is now shipped in 3.1.9

It'll say there are no lyrics (unless you're in fullscreen mode where it'll just be the album art alone) and the background should update to the cover-art
