### ISSUE TITLE
Every japanese song has incorrect romanized lyrics. Sometimes whole words are completely different. And some letters are not romanized at all.

### ISSUE THREAD

**Issue by Yokoo2** [surfbryce/beautiful-lyrics#933]
### Before you list your Songs:

- [X] IF you are reporting multiple songs, add ", ..." to the end of your title.
- [X] For every song you want to report, check Musixmatch or Apple Music and check to see if the Lyrics are any Different than what Beautiful Lyrics has.
- [X] For every song you want to report, point out the Incorrect Lyrics and what the correct ones are (ONLY IF the Lyrics aren't entirely incorrect).

### List Song Links

I've seen wrong romanized lyrics on [Ado](https://open.spotify.com/artist/6mEQK9m2krja6X1cfsAjfl?si=27b14331292a4905), but also on other Artists such as [DECO*27](https://open.spotify.com/artist/7kZTWx6cRLc0TSRPq1XBMP?si=7bc8188a8aec401c) and more.

**Comment by surfbryce** [comment]
@Yokoo2 Going to close this, you need to be WAY more specific. I am not Japanese nor do I speak the language. There is no possibly way for me to determine if what is being romanized is correct or not. The romanization code is not mine and is a public package maintained by those who understand the language significantly more than I do (which is none).

Additionally, it's possible that the lyrics themselves are just incorrect (which of course means the romanization is incorrect as well).

So first, on your part, I would look into seeing if the lyrics themselves (prior to romanization) are correct. If they are not, you should make incorrect-lyric reports for those songs without mentioning romanization (because at that point it's just a lyrics issue). IF the lyrics ARE correct then you need to make a bug report (and not a lyrics report) mentioning where the romanization is incorrect.

The likelihood that I'll be able to do anything is very low because I did not program that functionality. I also want to note that "every japanese song" is an extreme overstatement. Unless something recently has changed, I have a playlist that doesn't seem to have any faults in the romanization.
